// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: temporal/v1/service.proto

package temporalV1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/roadrunner-server/api-go/v6/temporal/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TemporalServiceName is the fully-qualified name of the TemporalService service.
	TemporalServiceName = "temporal.v1.TemporalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TemporalServiceRecordActivityHeartbeatProcedure is the fully-qualified name of the
	// TemporalService's RecordActivityHeartbeat RPC.
	TemporalServiceRecordActivityHeartbeatProcedure = "/temporal.v1.TemporalService/RecordActivityHeartbeat"
	// TemporalServiceGetActivityNamesProcedure is the fully-qualified name of the TemporalService's
	// GetActivityNames RPC.
	TemporalServiceGetActivityNamesProcedure = "/temporal.v1.TemporalService/GetActivityNames"
	// TemporalServiceGetWorkflowNamesProcedure is the fully-qualified name of the TemporalService's
	// GetWorkflowNames RPC.
	TemporalServiceGetWorkflowNamesProcedure = "/temporal.v1.TemporalService/GetWorkflowNames"
	// TemporalServiceReplayWorkflowProcedure is the fully-qualified name of the TemporalService's
	// ReplayWorkflow RPC.
	TemporalServiceReplayWorkflowProcedure = "/temporal.v1.TemporalService/ReplayWorkflow"
	// TemporalServiceDownloadWorkflowHistoryProcedure is the fully-qualified name of the
	// TemporalService's DownloadWorkflowHistory RPC.
	TemporalServiceDownloadWorkflowHistoryProcedure = "/temporal.v1.TemporalService/DownloadWorkflowHistory"
	// TemporalServiceReplayFromJSONProcedure is the fully-qualified name of the TemporalService's
	// ReplayFromJSON RPC.
	TemporalServiceReplayFromJSONProcedure = "/temporal.v1.TemporalService/ReplayFromJSON"
	// TemporalServiceReplayWorkflowHistoryProcedure is the fully-qualified name of the
	// TemporalService's ReplayWorkflowHistory RPC.
	TemporalServiceReplayWorkflowHistoryProcedure = "/temporal.v1.TemporalService/ReplayWorkflowHistory"
	// TemporalServiceUpdateAPIKeyProcedure is the fully-qualified name of the TemporalService's
	// UpdateAPIKey RPC.
	TemporalServiceUpdateAPIKeyProcedure = "/temporal.v1.TemporalService/UpdateAPIKey"
)

// TemporalServiceClient is a client for the temporal.v1.TemporalService service.
type TemporalServiceClient interface {
	RecordActivityHeartbeat(context.Context, *connect.Request[v1.RecordHeartbeatRequest]) (*connect.Response[v1.RecordHeartbeatResponse], error)
	GetActivityNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error)
	GetWorkflowNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error)
	ReplayWorkflow(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	DownloadWorkflowHistory(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	ReplayFromJSON(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	ReplayWorkflowHistory(context.Context, *connect.Request[v1.History]) (*connect.Response[v1.ReplayResponse], error)
	UpdateAPIKey(context.Context, *connect.Request[v1.UpdateAPIKeyRequest]) (*connect.Response[v1.UpdateAPIKeyResponse], error)
}

// NewTemporalServiceClient constructs a client for the temporal.v1.TemporalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTemporalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TemporalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	temporalServiceMethods := v1.File_temporal_v1_service_proto.Services().ByName("TemporalService").Methods()
	return &temporalServiceClient{
		recordActivityHeartbeat: connect.NewClient[v1.RecordHeartbeatRequest, v1.RecordHeartbeatResponse](
			httpClient,
			baseURL+TemporalServiceRecordActivityHeartbeatProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("RecordActivityHeartbeat")),
			connect.WithClientOptions(opts...),
		),
		getActivityNames: connect.NewClient[v1.GetNamesRequest, v1.NamesList](
			httpClient,
			baseURL+TemporalServiceGetActivityNamesProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("GetActivityNames")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getWorkflowNames: connect.NewClient[v1.GetNamesRequest, v1.NamesList](
			httpClient,
			baseURL+TemporalServiceGetWorkflowNamesProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("GetWorkflowNames")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		replayWorkflow: connect.NewClient[v1.ReplayRequest, v1.ReplayResponse](
			httpClient,
			baseURL+TemporalServiceReplayWorkflowProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("ReplayWorkflow")),
			connect.WithClientOptions(opts...),
		),
		downloadWorkflowHistory: connect.NewClient[v1.ReplayRequest, v1.ReplayResponse](
			httpClient,
			baseURL+TemporalServiceDownloadWorkflowHistoryProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("DownloadWorkflowHistory")),
			connect.WithClientOptions(opts...),
		),
		replayFromJSON: connect.NewClient[v1.ReplayRequest, v1.ReplayResponse](
			httpClient,
			baseURL+TemporalServiceReplayFromJSONProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("ReplayFromJSON")),
			connect.WithClientOptions(opts...),
		),
		replayWorkflowHistory: connect.NewClient[v1.History, v1.ReplayResponse](
			httpClient,
			baseURL+TemporalServiceReplayWorkflowHistoryProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("ReplayWorkflowHistory")),
			connect.WithClientOptions(opts...),
		),
		updateAPIKey: connect.NewClient[v1.UpdateAPIKeyRequest, v1.UpdateAPIKeyResponse](
			httpClient,
			baseURL+TemporalServiceUpdateAPIKeyProcedure,
			connect.WithSchema(temporalServiceMethods.ByName("UpdateAPIKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// temporalServiceClient implements TemporalServiceClient.
type temporalServiceClient struct {
	recordActivityHeartbeat *connect.Client[v1.RecordHeartbeatRequest, v1.RecordHeartbeatResponse]
	getActivityNames        *connect.Client[v1.GetNamesRequest, v1.NamesList]
	getWorkflowNames        *connect.Client[v1.GetNamesRequest, v1.NamesList]
	replayWorkflow          *connect.Client[v1.ReplayRequest, v1.ReplayResponse]
	downloadWorkflowHistory *connect.Client[v1.ReplayRequest, v1.ReplayResponse]
	replayFromJSON          *connect.Client[v1.ReplayRequest, v1.ReplayResponse]
	replayWorkflowHistory   *connect.Client[v1.History, v1.ReplayResponse]
	updateAPIKey            *connect.Client[v1.UpdateAPIKeyRequest, v1.UpdateAPIKeyResponse]
}

// RecordActivityHeartbeat calls temporal.v1.TemporalService.RecordActivityHeartbeat.
func (c *temporalServiceClient) RecordActivityHeartbeat(ctx context.Context, req *connect.Request[v1.RecordHeartbeatRequest]) (*connect.Response[v1.RecordHeartbeatResponse], error) {
	return c.recordActivityHeartbeat.CallUnary(ctx, req)
}

// GetActivityNames calls temporal.v1.TemporalService.GetActivityNames.
func (c *temporalServiceClient) GetActivityNames(ctx context.Context, req *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error) {
	return c.getActivityNames.CallUnary(ctx, req)
}

// GetWorkflowNames calls temporal.v1.TemporalService.GetWorkflowNames.
func (c *temporalServiceClient) GetWorkflowNames(ctx context.Context, req *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error) {
	return c.getWorkflowNames.CallUnary(ctx, req)
}

// ReplayWorkflow calls temporal.v1.TemporalService.ReplayWorkflow.
func (c *temporalServiceClient) ReplayWorkflow(ctx context.Context, req *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return c.replayWorkflow.CallUnary(ctx, req)
}

// DownloadWorkflowHistory calls temporal.v1.TemporalService.DownloadWorkflowHistory.
func (c *temporalServiceClient) DownloadWorkflowHistory(ctx context.Context, req *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return c.downloadWorkflowHistory.CallUnary(ctx, req)
}

// ReplayFromJSON calls temporal.v1.TemporalService.ReplayFromJSON.
func (c *temporalServiceClient) ReplayFromJSON(ctx context.Context, req *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return c.replayFromJSON.CallUnary(ctx, req)
}

// ReplayWorkflowHistory calls temporal.v1.TemporalService.ReplayWorkflowHistory.
func (c *temporalServiceClient) ReplayWorkflowHistory(ctx context.Context, req *connect.Request[v1.History]) (*connect.Response[v1.ReplayResponse], error) {
	return c.replayWorkflowHistory.CallUnary(ctx, req)
}

// UpdateAPIKey calls temporal.v1.TemporalService.UpdateAPIKey.
func (c *temporalServiceClient) UpdateAPIKey(ctx context.Context, req *connect.Request[v1.UpdateAPIKeyRequest]) (*connect.Response[v1.UpdateAPIKeyResponse], error) {
	return c.updateAPIKey.CallUnary(ctx, req)
}

// TemporalServiceHandler is an implementation of the temporal.v1.TemporalService service.
type TemporalServiceHandler interface {
	RecordActivityHeartbeat(context.Context, *connect.Request[v1.RecordHeartbeatRequest]) (*connect.Response[v1.RecordHeartbeatResponse], error)
	GetActivityNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error)
	GetWorkflowNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error)
	ReplayWorkflow(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	DownloadWorkflowHistory(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	ReplayFromJSON(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error)
	ReplayWorkflowHistory(context.Context, *connect.Request[v1.History]) (*connect.Response[v1.ReplayResponse], error)
	UpdateAPIKey(context.Context, *connect.Request[v1.UpdateAPIKeyRequest]) (*connect.Response[v1.UpdateAPIKeyResponse], error)
}

// NewTemporalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTemporalServiceHandler(svc TemporalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	temporalServiceMethods := v1.File_temporal_v1_service_proto.Services().ByName("TemporalService").Methods()
	temporalServiceRecordActivityHeartbeatHandler := connect.NewUnaryHandler(
		TemporalServiceRecordActivityHeartbeatProcedure,
		svc.RecordActivityHeartbeat,
		connect.WithSchema(temporalServiceMethods.ByName("RecordActivityHeartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceGetActivityNamesHandler := connect.NewUnaryHandler(
		TemporalServiceGetActivityNamesProcedure,
		svc.GetActivityNames,
		connect.WithSchema(temporalServiceMethods.ByName("GetActivityNames")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceGetWorkflowNamesHandler := connect.NewUnaryHandler(
		TemporalServiceGetWorkflowNamesProcedure,
		svc.GetWorkflowNames,
		connect.WithSchema(temporalServiceMethods.ByName("GetWorkflowNames")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceReplayWorkflowHandler := connect.NewUnaryHandler(
		TemporalServiceReplayWorkflowProcedure,
		svc.ReplayWorkflow,
		connect.WithSchema(temporalServiceMethods.ByName("ReplayWorkflow")),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceDownloadWorkflowHistoryHandler := connect.NewUnaryHandler(
		TemporalServiceDownloadWorkflowHistoryProcedure,
		svc.DownloadWorkflowHistory,
		connect.WithSchema(temporalServiceMethods.ByName("DownloadWorkflowHistory")),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceReplayFromJSONHandler := connect.NewUnaryHandler(
		TemporalServiceReplayFromJSONProcedure,
		svc.ReplayFromJSON,
		connect.WithSchema(temporalServiceMethods.ByName("ReplayFromJSON")),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceReplayWorkflowHistoryHandler := connect.NewUnaryHandler(
		TemporalServiceReplayWorkflowHistoryProcedure,
		svc.ReplayWorkflowHistory,
		connect.WithSchema(temporalServiceMethods.ByName("ReplayWorkflowHistory")),
		connect.WithHandlerOptions(opts...),
	)
	temporalServiceUpdateAPIKeyHandler := connect.NewUnaryHandler(
		TemporalServiceUpdateAPIKeyProcedure,
		svc.UpdateAPIKey,
		connect.WithSchema(temporalServiceMethods.ByName("UpdateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/temporal.v1.TemporalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TemporalServiceRecordActivityHeartbeatProcedure:
			temporalServiceRecordActivityHeartbeatHandler.ServeHTTP(w, r)
		case TemporalServiceGetActivityNamesProcedure:
			temporalServiceGetActivityNamesHandler.ServeHTTP(w, r)
		case TemporalServiceGetWorkflowNamesProcedure:
			temporalServiceGetWorkflowNamesHandler.ServeHTTP(w, r)
		case TemporalServiceReplayWorkflowProcedure:
			temporalServiceReplayWorkflowHandler.ServeHTTP(w, r)
		case TemporalServiceDownloadWorkflowHistoryProcedure:
			temporalServiceDownloadWorkflowHistoryHandler.ServeHTTP(w, r)
		case TemporalServiceReplayFromJSONProcedure:
			temporalServiceReplayFromJSONHandler.ServeHTTP(w, r)
		case TemporalServiceReplayWorkflowHistoryProcedure:
			temporalServiceReplayWorkflowHistoryHandler.ServeHTTP(w, r)
		case TemporalServiceUpdateAPIKeyProcedure:
			temporalServiceUpdateAPIKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTemporalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTemporalServiceHandler struct{}

func (UnimplementedTemporalServiceHandler) RecordActivityHeartbeat(context.Context, *connect.Request[v1.RecordHeartbeatRequest]) (*connect.Response[v1.RecordHeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.RecordActivityHeartbeat is not implemented"))
}

func (UnimplementedTemporalServiceHandler) GetActivityNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.GetActivityNames is not implemented"))
}

func (UnimplementedTemporalServiceHandler) GetWorkflowNames(context.Context, *connect.Request[v1.GetNamesRequest]) (*connect.Response[v1.NamesList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.GetWorkflowNames is not implemented"))
}

func (UnimplementedTemporalServiceHandler) ReplayWorkflow(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.ReplayWorkflow is not implemented"))
}

func (UnimplementedTemporalServiceHandler) DownloadWorkflowHistory(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.DownloadWorkflowHistory is not implemented"))
}

func (UnimplementedTemporalServiceHandler) ReplayFromJSON(context.Context, *connect.Request[v1.ReplayRequest]) (*connect.Response[v1.ReplayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.ReplayFromJSON is not implemented"))
}

func (UnimplementedTemporalServiceHandler) ReplayWorkflowHistory(context.Context, *connect.Request[v1.History]) (*connect.Response[v1.ReplayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.ReplayWorkflowHistory is not implemented"))
}

func (UnimplementedTemporalServiceHandler) UpdateAPIKey(context.Context, *connect.Request[v1.UpdateAPIKeyRequest]) (*connect.Response[v1.UpdateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("temporal.v1.TemporalService.UpdateAPIKey is not implemented"))
}
