// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: applogger/v2/service.proto

package apploggerV2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppLoggerService_Error_FullMethodName              = "/applogger.v2.AppLoggerService/Error"
	AppLoggerService_ErrorWithContext_FullMethodName   = "/applogger.v2.AppLoggerService/ErrorWithContext"
	AppLoggerService_Info_FullMethodName               = "/applogger.v2.AppLoggerService/Info"
	AppLoggerService_InfoWithContext_FullMethodName    = "/applogger.v2.AppLoggerService/InfoWithContext"
	AppLoggerService_Warning_FullMethodName            = "/applogger.v2.AppLoggerService/Warning"
	AppLoggerService_WarningWithContext_FullMethodName = "/applogger.v2.AppLoggerService/WarningWithContext"
	AppLoggerService_Debug_FullMethodName              = "/applogger.v2.AppLoggerService/Debug"
	AppLoggerService_DebugWithContext_FullMethodName   = "/applogger.v2.AppLoggerService/DebugWithContext"
	AppLoggerService_Log_FullMethodName                = "/applogger.v2.AppLoggerService/Log"
	AppLoggerService_LogWithContext_FullMethodName     = "/applogger.v2.AppLoggerService/LogWithContext"
)

// AppLoggerServiceClient is the client API for AppLoggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppLoggerServiceClient interface {
	Error(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	ErrorWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
	Info(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	InfoWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
	Warning(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	WarningWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
	Debug(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	DebugWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
	Log(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error)
	LogWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
}

type appLoggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppLoggerServiceClient(cc grpc.ClientConnInterface) AppLoggerServiceClient {
	return &appLoggerServiceClient{cc}
}

func (c *appLoggerServiceClient) Error(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_Error_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) ErrorWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_ErrorWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) Info(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) InfoWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_InfoWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) Warning(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_Warning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) WarningWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_WarningWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) Debug(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_Debug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) DebugWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_DebugWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) Log(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appLoggerServiceClient) LogWithContext(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AppLoggerService_LogWithContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppLoggerServiceServer is the server API for AppLoggerService service.
// All implementations must embed UnimplementedAppLoggerServiceServer
// for forward compatibility.
type AppLoggerServiceServer interface {
	Error(context.Context, *LogMessage) (*LogResponse, error)
	ErrorWithContext(context.Context, *LogEntry) (*LogResponse, error)
	Info(context.Context, *LogMessage) (*LogResponse, error)
	InfoWithContext(context.Context, *LogEntry) (*LogResponse, error)
	Warning(context.Context, *LogMessage) (*LogResponse, error)
	WarningWithContext(context.Context, *LogEntry) (*LogResponse, error)
	Debug(context.Context, *LogMessage) (*LogResponse, error)
	DebugWithContext(context.Context, *LogEntry) (*LogResponse, error)
	Log(context.Context, *LogMessage) (*LogResponse, error)
	LogWithContext(context.Context, *LogEntry) (*LogResponse, error)
	mustEmbedUnimplementedAppLoggerServiceServer()
}

// UnimplementedAppLoggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppLoggerServiceServer struct{}

func (UnimplementedAppLoggerServiceServer) Error(context.Context, *LogMessage) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Error not implemented")
}
func (UnimplementedAppLoggerServiceServer) ErrorWithContext(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ErrorWithContext not implemented")
}
func (UnimplementedAppLoggerServiceServer) Info(context.Context, *LogMessage) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAppLoggerServiceServer) InfoWithContext(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InfoWithContext not implemented")
}
func (UnimplementedAppLoggerServiceServer) Warning(context.Context, *LogMessage) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Warning not implemented")
}
func (UnimplementedAppLoggerServiceServer) WarningWithContext(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WarningWithContext not implemented")
}
func (UnimplementedAppLoggerServiceServer) Debug(context.Context, *LogMessage) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedAppLoggerServiceServer) DebugWithContext(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebugWithContext not implemented")
}
func (UnimplementedAppLoggerServiceServer) Log(context.Context, *LogMessage) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedAppLoggerServiceServer) LogWithContext(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LogWithContext not implemented")
}
func (UnimplementedAppLoggerServiceServer) mustEmbedUnimplementedAppLoggerServiceServer() {}
func (UnimplementedAppLoggerServiceServer) testEmbeddedByValue()                          {}

// UnsafeAppLoggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppLoggerServiceServer will
// result in compilation errors.
type UnsafeAppLoggerServiceServer interface {
	mustEmbedUnimplementedAppLoggerServiceServer()
}

func RegisterAppLoggerServiceServer(s grpc.ServiceRegistrar, srv AppLoggerServiceServer) {
	// If the following call panics, it indicates UnimplementedAppLoggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppLoggerService_ServiceDesc, srv)
}

func _AppLoggerService_Error_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).Error(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_Error_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).Error(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_ErrorWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).ErrorWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_ErrorWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).ErrorWithContext(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).Info(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_InfoWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).InfoWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_InfoWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).InfoWithContext(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_Warning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).Warning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_Warning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).Warning(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_WarningWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).WarningWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_WarningWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).WarningWithContext(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_Debug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).Debug(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_DebugWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).DebugWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_DebugWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).DebugWithContext(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).Log(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppLoggerService_LogWithContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppLoggerServiceServer).LogWithContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppLoggerService_LogWithContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppLoggerServiceServer).LogWithContext(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

// AppLoggerService_ServiceDesc is the grpc.ServiceDesc for AppLoggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppLoggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "applogger.v2.AppLoggerService",
	HandlerType: (*AppLoggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Error",
			Handler:    _AppLoggerService_Error_Handler,
		},
		{
			MethodName: "ErrorWithContext",
			Handler:    _AppLoggerService_ErrorWithContext_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _AppLoggerService_Info_Handler,
		},
		{
			MethodName: "InfoWithContext",
			Handler:    _AppLoggerService_InfoWithContext_Handler,
		},
		{
			MethodName: "Warning",
			Handler:    _AppLoggerService_Warning_Handler,
		},
		{
			MethodName: "WarningWithContext",
			Handler:    _AppLoggerService_WarningWithContext_Handler,
		},
		{
			MethodName: "Debug",
			Handler:    _AppLoggerService_Debug_Handler,
		},
		{
			MethodName: "DebugWithContext",
			Handler:    _AppLoggerService_DebugWithContext_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _AppLoggerService_Log_Handler,
		},
		{
			MethodName: "LogWithContext",
			Handler:    _AppLoggerService_LogWithContext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "applogger/v2/service.proto",
}
