// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: applogger/v2/service.proto

package apploggerV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogMessage carries a plain string log payload for the Error/Info/Warning/Debug/Log RPCs.
// Domain-specific so future fields (level, caller skip, etc.) can be added without breaking the wire.
type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_applogger_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_applogger_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_applogger_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_applogger_v2_service_proto protoreflect.FileDescriptor

const file_applogger_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapplogger/v2/service.proto\x12\fapplogger.v2\x1a\x1capplogger/v2/applogger.proto\"&\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa9\x05\n" +
	"\x10AppLoggerService\x12<\n" +
	"\x05Error\x12\x18.applogger.v2.LogMessage\x1a\x19.applogger.v2.LogResponse\x12E\n" +
	"\x10ErrorWithContext\x12\x16.applogger.v2.LogEntry\x1a\x19.applogger.v2.LogResponse\x12;\n" +
	"\x04Info\x12\x18.applogger.v2.LogMessage\x1a\x19.applogger.v2.LogResponse\x12D\n" +
	"\x0fInfoWithContext\x12\x16.applogger.v2.LogEntry\x1a\x19.applogger.v2.LogResponse\x12>\n" +
	"\aWarning\x12\x18.applogger.v2.LogMessage\x1a\x19.applogger.v2.LogResponse\x12G\n" +
	"\x12WarningWithContext\x12\x16.applogger.v2.LogEntry\x1a\x19.applogger.v2.LogResponse\x12<\n" +
	"\x05Debug\x12\x18.applogger.v2.LogMessage\x1a\x19.applogger.v2.LogResponse\x12E\n" +
	"\x10DebugWithContext\x12\x16.applogger.v2.LogEntry\x1a\x19.applogger.v2.LogResponse\x12:\n" +
	"\x03Log\x12\x18.applogger.v2.LogMessage\x1a\x19.applogger.v2.LogResponse\x12C\n" +
	"\x0eLogWithContext\x12\x16.applogger.v2.LogEntry\x1a\x19.applogger.v2.LogResponseB\x89\x01Z?github.com/roadrunner-server/api-go/v6/applogger/v2;apploggerV2\xca\x02\x1bRoadRunner\\AppLogger\\DTO\\V2\xe2\x02'RoadRunner\\AppLogger\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_applogger_v2_service_proto_rawDescOnce sync.Once
	file_applogger_v2_service_proto_rawDescData []byte
)

func file_applogger_v2_service_proto_rawDescGZIP() []byte {
	file_applogger_v2_service_proto_rawDescOnce.Do(func() {
		file_applogger_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_applogger_v2_service_proto_rawDesc), len(file_applogger_v2_service_proto_rawDesc)))
	})
	return file_applogger_v2_service_proto_rawDescData
}

var file_applogger_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_applogger_v2_service_proto_goTypes = []any{
	(*LogMessage)(nil),  // 0: applogger.v2.LogMessage
	(*LogEntry)(nil),    // 1: applogger.v2.LogEntry
	(*LogResponse)(nil), // 2: applogger.v2.LogResponse
}
var file_applogger_v2_service_proto_depIdxs = []int32{
	0,  // 0: applogger.v2.AppLoggerService.Error:input_type -> applogger.v2.LogMessage
	1,  // 1: applogger.v2.AppLoggerService.ErrorWithContext:input_type -> applogger.v2.LogEntry
	0,  // 2: applogger.v2.AppLoggerService.Info:input_type -> applogger.v2.LogMessage
	1,  // 3: applogger.v2.AppLoggerService.InfoWithContext:input_type -> applogger.v2.LogEntry
	0,  // 4: applogger.v2.AppLoggerService.Warning:input_type -> applogger.v2.LogMessage
	1,  // 5: applogger.v2.AppLoggerService.WarningWithContext:input_type -> applogger.v2.LogEntry
	0,  // 6: applogger.v2.AppLoggerService.Debug:input_type -> applogger.v2.LogMessage
	1,  // 7: applogger.v2.AppLoggerService.DebugWithContext:input_type -> applogger.v2.LogEntry
	0,  // 8: applogger.v2.AppLoggerService.Log:input_type -> applogger.v2.LogMessage
	1,  // 9: applogger.v2.AppLoggerService.LogWithContext:input_type -> applogger.v2.LogEntry
	2,  // 10: applogger.v2.AppLoggerService.Error:output_type -> applogger.v2.LogResponse
	2,  // 11: applogger.v2.AppLoggerService.ErrorWithContext:output_type -> applogger.v2.LogResponse
	2,  // 12: applogger.v2.AppLoggerService.Info:output_type -> applogger.v2.LogResponse
	2,  // 13: applogger.v2.AppLoggerService.InfoWithContext:output_type -> applogger.v2.LogResponse
	2,  // 14: applogger.v2.AppLoggerService.Warning:output_type -> applogger.v2.LogResponse
	2,  // 15: applogger.v2.AppLoggerService.WarningWithContext:output_type -> applogger.v2.LogResponse
	2,  // 16: applogger.v2.AppLoggerService.Debug:output_type -> applogger.v2.LogResponse
	2,  // 17: applogger.v2.AppLoggerService.DebugWithContext:output_type -> applogger.v2.LogResponse
	2,  // 18: applogger.v2.AppLoggerService.Log:output_type -> applogger.v2.LogResponse
	2,  // 19: applogger.v2.AppLoggerService.LogWithContext:output_type -> applogger.v2.LogResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_applogger_v2_service_proto_init() }
func file_applogger_v2_service_proto_init() {
	if File_applogger_v2_service_proto != nil {
		return
	}
	file_applogger_v2_applogger_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_applogger_v2_service_proto_rawDesc), len(file_applogger_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_applogger_v2_service_proto_goTypes,
		DependencyIndexes: file_applogger_v2_service_proto_depIdxs,
		MessageInfos:      file_applogger_v2_service_proto_msgTypes,
	}.Build()
	File_applogger_v2_service_proto = out.File
	file_applogger_v2_service_proto_goTypes = nil
	file_applogger_v2_service_proto_depIdxs = nil
}
