// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: status/v2/service.proto

package statusV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_status_v2_service_proto protoreflect.FileDescriptor

const file_status_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x17status/v2/service.proto\x12\tstatus.v2\x1a\x17status/v2/request.proto\x1a\x18status/v2/response.proto2\x8c\x01\n" +
	"\rStatusService\x12=\n" +
	"\x06Status\x12\x18.status.v2.StatusRequest\x1a\x19.status.v2.StatusResponse\x12<\n" +
	"\x05Ready\x12\x18.status.v2.StatusRequest\x1a\x19.status.v2.StatusResponseB}Z9github.com/roadrunner-server/api-go/v6/status/v2;statusV2\xca\x02\x18RoadRunner\\Status\\DTO\\V2\xe2\x02$RoadRunner\\Status\\DTO\\V2\\GPBMetadatab\x06proto3"

var file_status_v2_service_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: status.v2.StatusRequest
	(*StatusResponse)(nil), // 1: status.v2.StatusResponse
}
var file_status_v2_service_proto_depIdxs = []int32{
	0, // 0: status.v2.StatusService.Status:input_type -> status.v2.StatusRequest
	0, // 1: status.v2.StatusService.Ready:input_type -> status.v2.StatusRequest
	1, // 2: status.v2.StatusService.Status:output_type -> status.v2.StatusResponse
	1, // 3: status.v2.StatusService.Ready:output_type -> status.v2.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_status_v2_service_proto_init() }
func file_status_v2_service_proto_init() {
	if File_status_v2_service_proto != nil {
		return
	}
	file_status_v2_request_proto_init()
	file_status_v2_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_v2_service_proto_rawDesc), len(file_status_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_v2_service_proto_goTypes,
		DependencyIndexes: file_status_v2_service_proto_depIdxs,
	}.Build()
	File_status_v2_service_proto = out.File
	file_status_v2_service_proto_goTypes = nil
	file_status_v2_service_proto_depIdxs = nil
}
