// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: kv/v2/service.proto

package kvV2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/roadrunner-server/api-go/v6/kv/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// KvServiceName is the fully-qualified name of the KvService service.
	KvServiceName = "kv.v2.KvService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// KvServiceHasProcedure is the fully-qualified name of the KvService's Has RPC.
	KvServiceHasProcedure = "/kv.v2.KvService/Has"
	// KvServiceSetProcedure is the fully-qualified name of the KvService's Set RPC.
	KvServiceSetProcedure = "/kv.v2.KvService/Set"
	// KvServiceMGetProcedure is the fully-qualified name of the KvService's MGet RPC.
	KvServiceMGetProcedure = "/kv.v2.KvService/MGet"
	// KvServiceMExpireProcedure is the fully-qualified name of the KvService's MExpire RPC.
	KvServiceMExpireProcedure = "/kv.v2.KvService/MExpire"
	// KvServiceTTLProcedure is the fully-qualified name of the KvService's TTL RPC.
	KvServiceTTLProcedure = "/kv.v2.KvService/TTL"
	// KvServiceDeleteProcedure is the fully-qualified name of the KvService's Delete RPC.
	KvServiceDeleteProcedure = "/kv.v2.KvService/Delete"
	// KvServiceClearProcedure is the fully-qualified name of the KvService's Clear RPC.
	KvServiceClearProcedure = "/kv.v2.KvService/Clear"
)

// KvServiceClient is a client for the kv.v2.KvService service.
type KvServiceClient interface {
	Has(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Set(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	MGet(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	MExpire(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	TTL(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Delete(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Clear(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
}

// NewKvServiceClient constructs a client for the kv.v2.KvService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewKvServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) KvServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	kvServiceMethods := v2.File_kv_v2_service_proto.Services().ByName("KvService").Methods()
	return &kvServiceClient{
		has: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceHasProcedure,
			connect.WithSchema(kvServiceMethods.ByName("Has")),
			connect.WithClientOptions(opts...),
		),
		set: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceSetProcedure,
			connect.WithSchema(kvServiceMethods.ByName("Set")),
			connect.WithClientOptions(opts...),
		),
		mGet: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceMGetProcedure,
			connect.WithSchema(kvServiceMethods.ByName("MGet")),
			connect.WithClientOptions(opts...),
		),
		mExpire: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceMExpireProcedure,
			connect.WithSchema(kvServiceMethods.ByName("MExpire")),
			connect.WithClientOptions(opts...),
		),
		tTL: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceTTLProcedure,
			connect.WithSchema(kvServiceMethods.ByName("TTL")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceDeleteProcedure,
			connect.WithSchema(kvServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		clear: connect.NewClient[v2.KvRequest, v2.KvResponse](
			httpClient,
			baseURL+KvServiceClearProcedure,
			connect.WithSchema(kvServiceMethods.ByName("Clear")),
			connect.WithClientOptions(opts...),
		),
	}
}

// kvServiceClient implements KvServiceClient.
type kvServiceClient struct {
	has     *connect.Client[v2.KvRequest, v2.KvResponse]
	set     *connect.Client[v2.KvRequest, v2.KvResponse]
	mGet    *connect.Client[v2.KvRequest, v2.KvResponse]
	mExpire *connect.Client[v2.KvRequest, v2.KvResponse]
	tTL     *connect.Client[v2.KvRequest, v2.KvResponse]
	delete  *connect.Client[v2.KvRequest, v2.KvResponse]
	clear   *connect.Client[v2.KvRequest, v2.KvResponse]
}

// Has calls kv.v2.KvService.Has.
func (c *kvServiceClient) Has(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.has.CallUnary(ctx, req)
}

// Set calls kv.v2.KvService.Set.
func (c *kvServiceClient) Set(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.set.CallUnary(ctx, req)
}

// MGet calls kv.v2.KvService.MGet.
func (c *kvServiceClient) MGet(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.mGet.CallUnary(ctx, req)
}

// MExpire calls kv.v2.KvService.MExpire.
func (c *kvServiceClient) MExpire(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.mExpire.CallUnary(ctx, req)
}

// TTL calls kv.v2.KvService.TTL.
func (c *kvServiceClient) TTL(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.tTL.CallUnary(ctx, req)
}

// Delete calls kv.v2.KvService.Delete.
func (c *kvServiceClient) Delete(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Clear calls kv.v2.KvService.Clear.
func (c *kvServiceClient) Clear(ctx context.Context, req *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return c.clear.CallUnary(ctx, req)
}

// KvServiceHandler is an implementation of the kv.v2.KvService service.
type KvServiceHandler interface {
	Has(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Set(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	MGet(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	MExpire(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	TTL(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Delete(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
	Clear(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error)
}

// NewKvServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewKvServiceHandler(svc KvServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	kvServiceMethods := v2.File_kv_v2_service_proto.Services().ByName("KvService").Methods()
	kvServiceHasHandler := connect.NewUnaryHandler(
		KvServiceHasProcedure,
		svc.Has,
		connect.WithSchema(kvServiceMethods.ByName("Has")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceSetHandler := connect.NewUnaryHandler(
		KvServiceSetProcedure,
		svc.Set,
		connect.WithSchema(kvServiceMethods.ByName("Set")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceMGetHandler := connect.NewUnaryHandler(
		KvServiceMGetProcedure,
		svc.MGet,
		connect.WithSchema(kvServiceMethods.ByName("MGet")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceMExpireHandler := connect.NewUnaryHandler(
		KvServiceMExpireProcedure,
		svc.MExpire,
		connect.WithSchema(kvServiceMethods.ByName("MExpire")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceTTLHandler := connect.NewUnaryHandler(
		KvServiceTTLProcedure,
		svc.TTL,
		connect.WithSchema(kvServiceMethods.ByName("TTL")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceDeleteHandler := connect.NewUnaryHandler(
		KvServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(kvServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	kvServiceClearHandler := connect.NewUnaryHandler(
		KvServiceClearProcedure,
		svc.Clear,
		connect.WithSchema(kvServiceMethods.ByName("Clear")),
		connect.WithHandlerOptions(opts...),
	)
	return "/kv.v2.KvService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case KvServiceHasProcedure:
			kvServiceHasHandler.ServeHTTP(w, r)
		case KvServiceSetProcedure:
			kvServiceSetHandler.ServeHTTP(w, r)
		case KvServiceMGetProcedure:
			kvServiceMGetHandler.ServeHTTP(w, r)
		case KvServiceMExpireProcedure:
			kvServiceMExpireHandler.ServeHTTP(w, r)
		case KvServiceTTLProcedure:
			kvServiceTTLHandler.ServeHTTP(w, r)
		case KvServiceDeleteProcedure:
			kvServiceDeleteHandler.ServeHTTP(w, r)
		case KvServiceClearProcedure:
			kvServiceClearHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedKvServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedKvServiceHandler struct{}

func (UnimplementedKvServiceHandler) Has(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.Has is not implemented"))
}

func (UnimplementedKvServiceHandler) Set(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.Set is not implemented"))
}

func (UnimplementedKvServiceHandler) MGet(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.MGet is not implemented"))
}

func (UnimplementedKvServiceHandler) MExpire(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.MExpire is not implemented"))
}

func (UnimplementedKvServiceHandler) TTL(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.TTL is not implemented"))
}

func (UnimplementedKvServiceHandler) Delete(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.Delete is not implemented"))
}

func (UnimplementedKvServiceHandler) Clear(context.Context, *connect.Request[v2.KvRequest]) (*connect.Response[v2.KvResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("kv.v2.KvService.Clear is not implemented"))
}
