// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: resetter/v1/service.proto

package resetterV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_resetter_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resetter_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_resetter_v1_service_proto_rawDescGZIP(), []int{0}
}

type PluginsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []string               `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsList) Reset() {
	*x = PluginsList{}
	mi := &file_resetter_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsList) ProtoMessage() {}

func (x *PluginsList) ProtoReflect() protoreflect.Message {
	mi := &file_resetter_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsList.ProtoReflect.Descriptor instead.
func (*PluginsList) Descriptor() ([]byte, []int) {
	return file_resetter_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *PluginsList) GetPlugins() []string {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_resetter_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resetter_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_resetter_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ResetRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_resetter_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_resetter_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_resetter_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_resetter_v1_service_proto protoreflect.FileDescriptor

const file_resetter_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19resetter/v1/service.proto\x12\vresetter.v1\"\x14\n" +
	"\x12ListPluginsRequest\"'\n" +
	"\vPluginsList\x12\x18\n" +
	"\aplugins\x18\x01 \x03(\tR\aplugins\"&\n" +
	"\fResetRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x9b\x01\n" +
	"\x0fResetterService\x12M\n" +
	"\vListPlugins\x12\x1f.resetter.v1.ListPluginsRequest\x1a\x18.resetter.v1.PluginsList\"\x03\x90\x02\x01\x129\n" +
	"\x05Reset\x12\x19.resetter.v1.ResetRequest\x1a\x15.resetter.v1.ResponseB\x85\x01Z=github.com/roadrunner-server/api-go/v6/resetter/v1;resetterV1\xca\x02\x1aRoadRunner\\Resetter\\DTO\\V1\xe2\x02&RoadRunner\\Resetter\\DTO\\V1\\GPBMetadatab\x06proto3"

var (
	file_resetter_v1_service_proto_rawDescOnce sync.Once
	file_resetter_v1_service_proto_rawDescData []byte
)

func file_resetter_v1_service_proto_rawDescGZIP() []byte {
	file_resetter_v1_service_proto_rawDescOnce.Do(func() {
		file_resetter_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resetter_v1_service_proto_rawDesc), len(file_resetter_v1_service_proto_rawDesc)))
	})
	return file_resetter_v1_service_proto_rawDescData
}

var file_resetter_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_resetter_v1_service_proto_goTypes = []any{
	(*ListPluginsRequest)(nil), // 0: resetter.v1.ListPluginsRequest
	(*PluginsList)(nil),        // 1: resetter.v1.PluginsList
	(*ResetRequest)(nil),       // 2: resetter.v1.ResetRequest
	(*Response)(nil),           // 3: resetter.v1.Response
}
var file_resetter_v1_service_proto_depIdxs = []int32{
	0, // 0: resetter.v1.ResetterService.ListPlugins:input_type -> resetter.v1.ListPluginsRequest
	2, // 1: resetter.v1.ResetterService.Reset:input_type -> resetter.v1.ResetRequest
	1, // 2: resetter.v1.ResetterService.ListPlugins:output_type -> resetter.v1.PluginsList
	3, // 3: resetter.v1.ResetterService.Reset:output_type -> resetter.v1.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resetter_v1_service_proto_init() }
func file_resetter_v1_service_proto_init() {
	if File_resetter_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resetter_v1_service_proto_rawDesc), len(file_resetter_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resetter_v1_service_proto_goTypes,
		DependencyIndexes: file_resetter_v1_service_proto_depIdxs,
		MessageInfos:      file_resetter_v1_service_proto_msgTypes,
	}.Build()
	File_resetter_v1_service_proto = out.File
	file_resetter_v1_service_proto_goTypes = nil
	file_resetter_v1_service_proto_depIdxs = nil
}
