// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: kv/v2/service.proto

package kvV2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KvService_Has_FullMethodName     = "/kv.v2.KvService/Has"
	KvService_Set_FullMethodName     = "/kv.v2.KvService/Set"
	KvService_MGet_FullMethodName    = "/kv.v2.KvService/MGet"
	KvService_MExpire_FullMethodName = "/kv.v2.KvService/MExpire"
	KvService_TTL_FullMethodName     = "/kv.v2.KvService/TTL"
	KvService_Delete_FullMethodName  = "/kv.v2.KvService/Delete"
	KvService_Clear_FullMethodName   = "/kv.v2.KvService/Clear"
)

// KvServiceClient is the client API for KvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvServiceClient interface {
	Has(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	Set(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	MGet(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	MExpire(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	TTL(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	Delete(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
	Clear(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error)
}

type kvServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKvServiceClient(cc grpc.ClientConnInterface) KvServiceClient {
	return &kvServiceClient{cc}
}

func (c *kvServiceClient) Has(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_Has_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) Set(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) MGet(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_MGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) MExpire(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_MExpire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) TTL(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_TTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) Delete(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) Clear(ctx context.Context, in *KvRequest, opts ...grpc.CallOption) (*KvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KvResponse)
	err := c.cc.Invoke(ctx, KvService_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServiceServer is the server API for KvService service.
// All implementations must embed UnimplementedKvServiceServer
// for forward compatibility.
type KvServiceServer interface {
	Has(context.Context, *KvRequest) (*KvResponse, error)
	Set(context.Context, *KvRequest) (*KvResponse, error)
	MGet(context.Context, *KvRequest) (*KvResponse, error)
	MExpire(context.Context, *KvRequest) (*KvResponse, error)
	TTL(context.Context, *KvRequest) (*KvResponse, error)
	Delete(context.Context, *KvRequest) (*KvResponse, error)
	Clear(context.Context, *KvRequest) (*KvResponse, error)
	mustEmbedUnimplementedKvServiceServer()
}

// UnimplementedKvServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKvServiceServer struct{}

func (UnimplementedKvServiceServer) Has(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Has not implemented")
}
func (UnimplementedKvServiceServer) Set(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedKvServiceServer) MGet(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MGet not implemented")
}
func (UnimplementedKvServiceServer) MExpire(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MExpire not implemented")
}
func (UnimplementedKvServiceServer) TTL(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TTL not implemented")
}
func (UnimplementedKvServiceServer) Delete(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedKvServiceServer) Clear(context.Context, *KvRequest) (*KvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedKvServiceServer) mustEmbedUnimplementedKvServiceServer() {}
func (UnimplementedKvServiceServer) testEmbeddedByValue()                   {}

// UnsafeKvServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvServiceServer will
// result in compilation errors.
type UnsafeKvServiceServer interface {
	mustEmbedUnimplementedKvServiceServer()
}

func RegisterKvServiceServer(s grpc.ServiceRegistrar, srv KvServiceServer) {
	// If the following call panics, it indicates UnimplementedKvServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KvService_ServiceDesc, srv)
}

func _KvService_Has_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).Has(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_Has_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).Has(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).Set(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_MGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).MGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_MGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).MGet(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_MExpire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).MExpire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_MExpire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).MExpire(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_TTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).TTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_TTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).TTL(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).Delete(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KvService_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).Clear(ctx, req.(*KvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KvService_ServiceDesc is the grpc.ServiceDesc for KvService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KvService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kv.v2.KvService",
	HandlerType: (*KvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Has",
			Handler:    _KvService_Has_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _KvService_Set_Handler,
		},
		{
			MethodName: "MGet",
			Handler:    _KvService_MGet_Handler,
		},
		{
			MethodName: "MExpire",
			Handler:    _KvService_MExpire_Handler,
		},
		{
			MethodName: "TTL",
			Handler:    _KvService_TTL_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _KvService_Delete_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _KvService_Clear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv/v2/service.proto",
}
