// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: resetter/v1/service.proto

package resetterV1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/roadrunner-server/api-go/v6/resetter/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResetterServiceName is the fully-qualified name of the ResetterService service.
	ResetterServiceName = "resetter.v1.ResetterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResetterServiceListPluginsProcedure is the fully-qualified name of the ResetterService's
	// ListPlugins RPC.
	ResetterServiceListPluginsProcedure = "/resetter.v1.ResetterService/ListPlugins"
	// ResetterServiceResetProcedure is the fully-qualified name of the ResetterService's Reset RPC.
	ResetterServiceResetProcedure = "/resetter.v1.ResetterService/Reset"
)

// ResetterServiceClient is a client for the resetter.v1.ResetterService service.
type ResetterServiceClient interface {
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.PluginsList], error)
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.Response], error)
}

// NewResetterServiceClient constructs a client for the resetter.v1.ResetterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResetterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResetterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resetterServiceMethods := v1.File_resetter_v1_service_proto.Services().ByName("ResetterService").Methods()
	return &resetterServiceClient{
		listPlugins: connect.NewClient[v1.ListPluginsRequest, v1.PluginsList](
			httpClient,
			baseURL+ResetterServiceListPluginsProcedure,
			connect.WithSchema(resetterServiceMethods.ByName("ListPlugins")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		reset: connect.NewClient[v1.ResetRequest, v1.Response](
			httpClient,
			baseURL+ResetterServiceResetProcedure,
			connect.WithSchema(resetterServiceMethods.ByName("Reset")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resetterServiceClient implements ResetterServiceClient.
type resetterServiceClient struct {
	listPlugins *connect.Client[v1.ListPluginsRequest, v1.PluginsList]
	reset       *connect.Client[v1.ResetRequest, v1.Response]
}

// ListPlugins calls resetter.v1.ResetterService.ListPlugins.
func (c *resetterServiceClient) ListPlugins(ctx context.Context, req *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.PluginsList], error) {
	return c.listPlugins.CallUnary(ctx, req)
}

// Reset calls resetter.v1.ResetterService.Reset.
func (c *resetterServiceClient) Reset(ctx context.Context, req *connect.Request[v1.ResetRequest]) (*connect.Response[v1.Response], error) {
	return c.reset.CallUnary(ctx, req)
}

// ResetterServiceHandler is an implementation of the resetter.v1.ResetterService service.
type ResetterServiceHandler interface {
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.PluginsList], error)
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.Response], error)
}

// NewResetterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResetterServiceHandler(svc ResetterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resetterServiceMethods := v1.File_resetter_v1_service_proto.Services().ByName("ResetterService").Methods()
	resetterServiceListPluginsHandler := connect.NewUnaryHandler(
		ResetterServiceListPluginsProcedure,
		svc.ListPlugins,
		connect.WithSchema(resetterServiceMethods.ByName("ListPlugins")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	resetterServiceResetHandler := connect.NewUnaryHandler(
		ResetterServiceResetProcedure,
		svc.Reset,
		connect.WithSchema(resetterServiceMethods.ByName("Reset")),
		connect.WithHandlerOptions(opts...),
	)
	return "/resetter.v1.ResetterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResetterServiceListPluginsProcedure:
			resetterServiceListPluginsHandler.ServeHTTP(w, r)
		case ResetterServiceResetProcedure:
			resetterServiceResetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResetterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResetterServiceHandler struct{}

func (UnimplementedResetterServiceHandler) ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.PluginsList], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resetter.v1.ResetterService.ListPlugins is not implemented"))
}

func (UnimplementedResetterServiceHandler) Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resetter.v1.ResetterService.Reset is not implemented"))
}
