// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: service/v1/service_rpc.proto

package serviceV1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/roadrunner-server/api-go/v6/service/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceManagerName is the fully-qualified name of the ServiceManager service.
	ServiceManagerName = "service.v1.ServiceManager"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceManagerCreateServiceProcedure is the fully-qualified name of the ServiceManager's
	// CreateService RPC.
	ServiceManagerCreateServiceProcedure = "/service.v1.ServiceManager/CreateService"
	// ServiceManagerTerminateProcedure is the fully-qualified name of the ServiceManager's Terminate
	// RPC.
	ServiceManagerTerminateProcedure = "/service.v1.ServiceManager/Terminate"
	// ServiceManagerRestartProcedure is the fully-qualified name of the ServiceManager's Restart RPC.
	ServiceManagerRestartProcedure = "/service.v1.ServiceManager/Restart"
	// ServiceManagerGetStatusProcedure is the fully-qualified name of the ServiceManager's GetStatus
	// RPC.
	ServiceManagerGetStatusProcedure = "/service.v1.ServiceManager/GetStatus"
	// ServiceManagerGetStatusesProcedure is the fully-qualified name of the ServiceManager's
	// GetStatuses RPC.
	ServiceManagerGetStatusesProcedure = "/service.v1.ServiceManager/GetStatuses"
	// ServiceManagerListServicesProcedure is the fully-qualified name of the ServiceManager's
	// ListServices RPC.
	ServiceManagerListServicesProcedure = "/service.v1.ServiceManager/ListServices"
)

// ServiceManagerClient is a client for the service.v1.ServiceManager service.
type ServiceManagerClient interface {
	CreateService(context.Context, *connect.Request[v1.Create]) (*connect.Response[v1.Response], error)
	Terminate(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error)
	Restart(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error)
	GetStatus(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Status], error)
	GetStatuses(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Statuses], error)
	ListServices(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.List], error)
}

// NewServiceManagerClient constructs a client for the service.v1.ServiceManager service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceManagerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceManagerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceManagerMethods := v1.File_service_v1_service_rpc_proto.Services().ByName("ServiceManager").Methods()
	return &serviceManagerClient{
		createService: connect.NewClient[v1.Create, v1.Response](
			httpClient,
			baseURL+ServiceManagerCreateServiceProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("CreateService")),
			connect.WithClientOptions(opts...),
		),
		terminate: connect.NewClient[v1.Service, v1.Response](
			httpClient,
			baseURL+ServiceManagerTerminateProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("Terminate")),
			connect.WithClientOptions(opts...),
		),
		restart: connect.NewClient[v1.Service, v1.Response](
			httpClient,
			baseURL+ServiceManagerRestartProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("Restart")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[v1.Service, v1.Status](
			httpClient,
			baseURL+ServiceManagerGetStatusProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("GetStatus")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getStatuses: connect.NewClient[v1.Service, v1.Statuses](
			httpClient,
			baseURL+ServiceManagerGetStatusesProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("GetStatuses")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[v1.Service, v1.List](
			httpClient,
			baseURL+ServiceManagerListServicesProcedure,
			connect.WithSchema(serviceManagerMethods.ByName("ListServices")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceManagerClient implements ServiceManagerClient.
type serviceManagerClient struct {
	createService *connect.Client[v1.Create, v1.Response]
	terminate     *connect.Client[v1.Service, v1.Response]
	restart       *connect.Client[v1.Service, v1.Response]
	getStatus     *connect.Client[v1.Service, v1.Status]
	getStatuses   *connect.Client[v1.Service, v1.Statuses]
	listServices  *connect.Client[v1.Service, v1.List]
}

// CreateService calls service.v1.ServiceManager.CreateService.
func (c *serviceManagerClient) CreateService(ctx context.Context, req *connect.Request[v1.Create]) (*connect.Response[v1.Response], error) {
	return c.createService.CallUnary(ctx, req)
}

// Terminate calls service.v1.ServiceManager.Terminate.
func (c *serviceManagerClient) Terminate(ctx context.Context, req *connect.Request[v1.Service]) (*connect.Response[v1.Response], error) {
	return c.terminate.CallUnary(ctx, req)
}

// Restart calls service.v1.ServiceManager.Restart.
func (c *serviceManagerClient) Restart(ctx context.Context, req *connect.Request[v1.Service]) (*connect.Response[v1.Response], error) {
	return c.restart.CallUnary(ctx, req)
}

// GetStatus calls service.v1.ServiceManager.GetStatus.
func (c *serviceManagerClient) GetStatus(ctx context.Context, req *connect.Request[v1.Service]) (*connect.Response[v1.Status], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// GetStatuses calls service.v1.ServiceManager.GetStatuses.
func (c *serviceManagerClient) GetStatuses(ctx context.Context, req *connect.Request[v1.Service]) (*connect.Response[v1.Statuses], error) {
	return c.getStatuses.CallUnary(ctx, req)
}

// ListServices calls service.v1.ServiceManager.ListServices.
func (c *serviceManagerClient) ListServices(ctx context.Context, req *connect.Request[v1.Service]) (*connect.Response[v1.List], error) {
	return c.listServices.CallUnary(ctx, req)
}

// ServiceManagerHandler is an implementation of the service.v1.ServiceManager service.
type ServiceManagerHandler interface {
	CreateService(context.Context, *connect.Request[v1.Create]) (*connect.Response[v1.Response], error)
	Terminate(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error)
	Restart(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error)
	GetStatus(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Status], error)
	GetStatuses(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Statuses], error)
	ListServices(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.List], error)
}

// NewServiceManagerHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceManagerHandler(svc ServiceManagerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceManagerMethods := v1.File_service_v1_service_rpc_proto.Services().ByName("ServiceManager").Methods()
	serviceManagerCreateServiceHandler := connect.NewUnaryHandler(
		ServiceManagerCreateServiceProcedure,
		svc.CreateService,
		connect.WithSchema(serviceManagerMethods.ByName("CreateService")),
		connect.WithHandlerOptions(opts...),
	)
	serviceManagerTerminateHandler := connect.NewUnaryHandler(
		ServiceManagerTerminateProcedure,
		svc.Terminate,
		connect.WithSchema(serviceManagerMethods.ByName("Terminate")),
		connect.WithHandlerOptions(opts...),
	)
	serviceManagerRestartHandler := connect.NewUnaryHandler(
		ServiceManagerRestartProcedure,
		svc.Restart,
		connect.WithSchema(serviceManagerMethods.ByName("Restart")),
		connect.WithHandlerOptions(opts...),
	)
	serviceManagerGetStatusHandler := connect.NewUnaryHandler(
		ServiceManagerGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(serviceManagerMethods.ByName("GetStatus")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	serviceManagerGetStatusesHandler := connect.NewUnaryHandler(
		ServiceManagerGetStatusesProcedure,
		svc.GetStatuses,
		connect.WithSchema(serviceManagerMethods.ByName("GetStatuses")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	serviceManagerListServicesHandler := connect.NewUnaryHandler(
		ServiceManagerListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(serviceManagerMethods.ByName("ListServices")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/service.v1.ServiceManager/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceManagerCreateServiceProcedure:
			serviceManagerCreateServiceHandler.ServeHTTP(w, r)
		case ServiceManagerTerminateProcedure:
			serviceManagerTerminateHandler.ServeHTTP(w, r)
		case ServiceManagerRestartProcedure:
			serviceManagerRestartHandler.ServeHTTP(w, r)
		case ServiceManagerGetStatusProcedure:
			serviceManagerGetStatusHandler.ServeHTTP(w, r)
		case ServiceManagerGetStatusesProcedure:
			serviceManagerGetStatusesHandler.ServeHTTP(w, r)
		case ServiceManagerListServicesProcedure:
			serviceManagerListServicesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceManagerHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceManagerHandler struct{}

func (UnimplementedServiceManagerHandler) CreateService(context.Context, *connect.Request[v1.Create]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.CreateService is not implemented"))
}

func (UnimplementedServiceManagerHandler) Terminate(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.Terminate is not implemented"))
}

func (UnimplementedServiceManagerHandler) Restart(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.Restart is not implemented"))
}

func (UnimplementedServiceManagerHandler) GetStatus(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Status], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.GetStatus is not implemented"))
}

func (UnimplementedServiceManagerHandler) GetStatuses(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.Statuses], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.GetStatuses is not implemented"))
}

func (UnimplementedServiceManagerHandler) ListServices(context.Context, *connect.Request[v1.Service]) (*connect.Response[v1.List], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("service.v1.ServiceManager.ListServices is not implemented"))
}
