// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: applogger/v2/service.proto

package apploggerV2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/roadrunner-server/api-go/v6/applogger/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AppLoggerServiceName is the fully-qualified name of the AppLoggerService service.
	AppLoggerServiceName = "applogger.v2.AppLoggerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AppLoggerServiceErrorProcedure is the fully-qualified name of the AppLoggerService's Error RPC.
	AppLoggerServiceErrorProcedure = "/applogger.v2.AppLoggerService/Error"
	// AppLoggerServiceErrorWithContextProcedure is the fully-qualified name of the AppLoggerService's
	// ErrorWithContext RPC.
	AppLoggerServiceErrorWithContextProcedure = "/applogger.v2.AppLoggerService/ErrorWithContext"
	// AppLoggerServiceInfoProcedure is the fully-qualified name of the AppLoggerService's Info RPC.
	AppLoggerServiceInfoProcedure = "/applogger.v2.AppLoggerService/Info"
	// AppLoggerServiceInfoWithContextProcedure is the fully-qualified name of the AppLoggerService's
	// InfoWithContext RPC.
	AppLoggerServiceInfoWithContextProcedure = "/applogger.v2.AppLoggerService/InfoWithContext"
	// AppLoggerServiceWarningProcedure is the fully-qualified name of the AppLoggerService's Warning
	// RPC.
	AppLoggerServiceWarningProcedure = "/applogger.v2.AppLoggerService/Warning"
	// AppLoggerServiceWarningWithContextProcedure is the fully-qualified name of the AppLoggerService's
	// WarningWithContext RPC.
	AppLoggerServiceWarningWithContextProcedure = "/applogger.v2.AppLoggerService/WarningWithContext"
	// AppLoggerServiceDebugProcedure is the fully-qualified name of the AppLoggerService's Debug RPC.
	AppLoggerServiceDebugProcedure = "/applogger.v2.AppLoggerService/Debug"
	// AppLoggerServiceDebugWithContextProcedure is the fully-qualified name of the AppLoggerService's
	// DebugWithContext RPC.
	AppLoggerServiceDebugWithContextProcedure = "/applogger.v2.AppLoggerService/DebugWithContext"
	// AppLoggerServiceLogProcedure is the fully-qualified name of the AppLoggerService's Log RPC.
	AppLoggerServiceLogProcedure = "/applogger.v2.AppLoggerService/Log"
	// AppLoggerServiceLogWithContextProcedure is the fully-qualified name of the AppLoggerService's
	// LogWithContext RPC.
	AppLoggerServiceLogWithContextProcedure = "/applogger.v2.AppLoggerService/LogWithContext"
)

// AppLoggerServiceClient is a client for the applogger.v2.AppLoggerService service.
type AppLoggerServiceClient interface {
	Error(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	ErrorWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Info(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	InfoWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Warning(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	WarningWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Debug(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	DebugWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Log(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	LogWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
}

// NewAppLoggerServiceClient constructs a client for the applogger.v2.AppLoggerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAppLoggerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AppLoggerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	appLoggerServiceMethods := v2.File_applogger_v2_service_proto.Services().ByName("AppLoggerService").Methods()
	return &appLoggerServiceClient{
		error: connect.NewClient[v2.LogMessage, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceErrorProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("Error")),
			connect.WithClientOptions(opts...),
		),
		errorWithContext: connect.NewClient[v2.LogEntry, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceErrorWithContextProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("ErrorWithContext")),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[v2.LogMessage, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceInfoProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("Info")),
			connect.WithClientOptions(opts...),
		),
		infoWithContext: connect.NewClient[v2.LogEntry, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceInfoWithContextProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("InfoWithContext")),
			connect.WithClientOptions(opts...),
		),
		warning: connect.NewClient[v2.LogMessage, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceWarningProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("Warning")),
			connect.WithClientOptions(opts...),
		),
		warningWithContext: connect.NewClient[v2.LogEntry, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceWarningWithContextProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("WarningWithContext")),
			connect.WithClientOptions(opts...),
		),
		debug: connect.NewClient[v2.LogMessage, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceDebugProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("Debug")),
			connect.WithClientOptions(opts...),
		),
		debugWithContext: connect.NewClient[v2.LogEntry, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceDebugWithContextProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("DebugWithContext")),
			connect.WithClientOptions(opts...),
		),
		log: connect.NewClient[v2.LogMessage, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceLogProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
		logWithContext: connect.NewClient[v2.LogEntry, v2.LogResponse](
			httpClient,
			baseURL+AppLoggerServiceLogWithContextProcedure,
			connect.WithSchema(appLoggerServiceMethods.ByName("LogWithContext")),
			connect.WithClientOptions(opts...),
		),
	}
}

// appLoggerServiceClient implements AppLoggerServiceClient.
type appLoggerServiceClient struct {
	error              *connect.Client[v2.LogMessage, v2.LogResponse]
	errorWithContext   *connect.Client[v2.LogEntry, v2.LogResponse]
	info               *connect.Client[v2.LogMessage, v2.LogResponse]
	infoWithContext    *connect.Client[v2.LogEntry, v2.LogResponse]
	warning            *connect.Client[v2.LogMessage, v2.LogResponse]
	warningWithContext *connect.Client[v2.LogEntry, v2.LogResponse]
	debug              *connect.Client[v2.LogMessage, v2.LogResponse]
	debugWithContext   *connect.Client[v2.LogEntry, v2.LogResponse]
	log                *connect.Client[v2.LogMessage, v2.LogResponse]
	logWithContext     *connect.Client[v2.LogEntry, v2.LogResponse]
}

// Error calls applogger.v2.AppLoggerService.Error.
func (c *appLoggerServiceClient) Error(ctx context.Context, req *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return c.error.CallUnary(ctx, req)
}

// ErrorWithContext calls applogger.v2.AppLoggerService.ErrorWithContext.
func (c *appLoggerServiceClient) ErrorWithContext(ctx context.Context, req *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return c.errorWithContext.CallUnary(ctx, req)
}

// Info calls applogger.v2.AppLoggerService.Info.
func (c *appLoggerServiceClient) Info(ctx context.Context, req *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// InfoWithContext calls applogger.v2.AppLoggerService.InfoWithContext.
func (c *appLoggerServiceClient) InfoWithContext(ctx context.Context, req *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return c.infoWithContext.CallUnary(ctx, req)
}

// Warning calls applogger.v2.AppLoggerService.Warning.
func (c *appLoggerServiceClient) Warning(ctx context.Context, req *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return c.warning.CallUnary(ctx, req)
}

// WarningWithContext calls applogger.v2.AppLoggerService.WarningWithContext.
func (c *appLoggerServiceClient) WarningWithContext(ctx context.Context, req *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return c.warningWithContext.CallUnary(ctx, req)
}

// Debug calls applogger.v2.AppLoggerService.Debug.
func (c *appLoggerServiceClient) Debug(ctx context.Context, req *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return c.debug.CallUnary(ctx, req)
}

// DebugWithContext calls applogger.v2.AppLoggerService.DebugWithContext.
func (c *appLoggerServiceClient) DebugWithContext(ctx context.Context, req *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return c.debugWithContext.CallUnary(ctx, req)
}

// Log calls applogger.v2.AppLoggerService.Log.
func (c *appLoggerServiceClient) Log(ctx context.Context, req *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return c.log.CallUnary(ctx, req)
}

// LogWithContext calls applogger.v2.AppLoggerService.LogWithContext.
func (c *appLoggerServiceClient) LogWithContext(ctx context.Context, req *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return c.logWithContext.CallUnary(ctx, req)
}

// AppLoggerServiceHandler is an implementation of the applogger.v2.AppLoggerService service.
type AppLoggerServiceHandler interface {
	Error(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	ErrorWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Info(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	InfoWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Warning(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	WarningWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Debug(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	DebugWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
	Log(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error)
	LogWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error)
}

// NewAppLoggerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAppLoggerServiceHandler(svc AppLoggerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	appLoggerServiceMethods := v2.File_applogger_v2_service_proto.Services().ByName("AppLoggerService").Methods()
	appLoggerServiceErrorHandler := connect.NewUnaryHandler(
		AppLoggerServiceErrorProcedure,
		svc.Error,
		connect.WithSchema(appLoggerServiceMethods.ByName("Error")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceErrorWithContextHandler := connect.NewUnaryHandler(
		AppLoggerServiceErrorWithContextProcedure,
		svc.ErrorWithContext,
		connect.WithSchema(appLoggerServiceMethods.ByName("ErrorWithContext")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceInfoHandler := connect.NewUnaryHandler(
		AppLoggerServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(appLoggerServiceMethods.ByName("Info")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceInfoWithContextHandler := connect.NewUnaryHandler(
		AppLoggerServiceInfoWithContextProcedure,
		svc.InfoWithContext,
		connect.WithSchema(appLoggerServiceMethods.ByName("InfoWithContext")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceWarningHandler := connect.NewUnaryHandler(
		AppLoggerServiceWarningProcedure,
		svc.Warning,
		connect.WithSchema(appLoggerServiceMethods.ByName("Warning")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceWarningWithContextHandler := connect.NewUnaryHandler(
		AppLoggerServiceWarningWithContextProcedure,
		svc.WarningWithContext,
		connect.WithSchema(appLoggerServiceMethods.ByName("WarningWithContext")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceDebugHandler := connect.NewUnaryHandler(
		AppLoggerServiceDebugProcedure,
		svc.Debug,
		connect.WithSchema(appLoggerServiceMethods.ByName("Debug")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceDebugWithContextHandler := connect.NewUnaryHandler(
		AppLoggerServiceDebugWithContextProcedure,
		svc.DebugWithContext,
		connect.WithSchema(appLoggerServiceMethods.ByName("DebugWithContext")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceLogHandler := connect.NewUnaryHandler(
		AppLoggerServiceLogProcedure,
		svc.Log,
		connect.WithSchema(appLoggerServiceMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	appLoggerServiceLogWithContextHandler := connect.NewUnaryHandler(
		AppLoggerServiceLogWithContextProcedure,
		svc.LogWithContext,
		connect.WithSchema(appLoggerServiceMethods.ByName("LogWithContext")),
		connect.WithHandlerOptions(opts...),
	)
	return "/applogger.v2.AppLoggerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AppLoggerServiceErrorProcedure:
			appLoggerServiceErrorHandler.ServeHTTP(w, r)
		case AppLoggerServiceErrorWithContextProcedure:
			appLoggerServiceErrorWithContextHandler.ServeHTTP(w, r)
		case AppLoggerServiceInfoProcedure:
			appLoggerServiceInfoHandler.ServeHTTP(w, r)
		case AppLoggerServiceInfoWithContextProcedure:
			appLoggerServiceInfoWithContextHandler.ServeHTTP(w, r)
		case AppLoggerServiceWarningProcedure:
			appLoggerServiceWarningHandler.ServeHTTP(w, r)
		case AppLoggerServiceWarningWithContextProcedure:
			appLoggerServiceWarningWithContextHandler.ServeHTTP(w, r)
		case AppLoggerServiceDebugProcedure:
			appLoggerServiceDebugHandler.ServeHTTP(w, r)
		case AppLoggerServiceDebugWithContextProcedure:
			appLoggerServiceDebugWithContextHandler.ServeHTTP(w, r)
		case AppLoggerServiceLogProcedure:
			appLoggerServiceLogHandler.ServeHTTP(w, r)
		case AppLoggerServiceLogWithContextProcedure:
			appLoggerServiceLogWithContextHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAppLoggerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAppLoggerServiceHandler struct{}

func (UnimplementedAppLoggerServiceHandler) Error(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.Error is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) ErrorWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.ErrorWithContext is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) Info(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.Info is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) InfoWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.InfoWithContext is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) Warning(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.Warning is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) WarningWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.WarningWithContext is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) Debug(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.Debug is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) DebugWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.DebugWithContext is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) Log(context.Context, *connect.Request[v2.LogMessage]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.Log is not implemented"))
}

func (UnimplementedAppLoggerServiceHandler) LogWithContext(context.Context, *connect.Request[v2.LogEntry]) (*connect.Response[v2.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("applogger.v2.AppLoggerService.LogWithContext is not implemented"))
}
