// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobs/v2/request.proto

package jobsV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobsHandlerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobsHandlerRequest) Reset() {
	*x = JobsHandlerRequest{}
	mi := &file_jobs_v2_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobsHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsHandlerRequest) ProtoMessage() {}

func (x *JobsHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_v2_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsHandlerRequest.ProtoReflect.Descriptor instead.
func (*JobsHandlerRequest) Descriptor() ([]byte, []int) {
	return file_jobs_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *JobsHandlerRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type PushBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Jobs  []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// request headers
	Headers       map[string]*JobHeaderValue `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushBatchRequest) Reset() {
	*x = PushBatchRequest{}
	mi := &file_jobs_v2_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBatchRequest) ProtoMessage() {}

func (x *PushBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_v2_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBatchRequest.ProtoReflect.Descriptor instead.
func (*PushBatchRequest) Descriptor() ([]byte, []int) {
	return file_jobs_v2_request_proto_rawDescGZIP(), []int{1}
}

func (x *PushBatchRequest) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *PushBatchRequest) GetHeaders() map[string]*JobHeaderValue {
	if x != nil {
		return x.Headers
	}
	return nil
}

type DeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      map[string]string      `protobuf:"bytes,1,rep,name=pipeline,proto3" json:"pipeline,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareRequest) Reset() {
	*x = DeclareRequest{}
	mi := &file_jobs_v2_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareRequest) ProtoMessage() {}

func (x *DeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_v2_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareRequest.ProtoReflect.Descriptor instead.
func (*DeclareRequest) Descriptor() ([]byte, []int) {
	return file_jobs_v2_request_proto_rawDescGZIP(), []int{2}
}

func (x *DeclareRequest) GetPipeline() map[string]string {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

var File_jobs_v2_request_proto protoreflect.FileDescriptor

const file_jobs_v2_request_proto_rawDesc = "" +
	"\n" +
	"\x15jobs/v2/request.proto\x12\ajobs.v2\x1a\x12jobs/v2/jobs.proto\"4\n" +
	"\x12JobsHandlerRequest\x12\x1e\n" +
	"\x03job\x18\x01 \x01(\v2\f.jobs.v2.JobR\x03job\"\xcb\x01\n" +
	"\x10PushBatchRequest\x12 \n" +
	"\x04jobs\x18\x01 \x03(\v2\f.jobs.v2.JobR\x04jobs\x12@\n" +
	"\aheaders\x18\x02 \x03(\v2&.jobs.v2.PushBatchRequest.HeadersEntryR\aheaders\x1aS\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.jobs.v2.JobHeaderValueR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0eDeclareRequest\x12A\n" +
	"\bpipeline\x18\x01 \x03(\v2%.jobs.v2.DeclareRequest.PipelineEntryR\bpipeline\x1a;\n" +
	"\rPipelineEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BuZ5github.com/roadrunner-server/api-go/v6/jobs/v2;jobsV2\xca\x02\x16RoadRunner\\Jobs\\DTO\\V2\xe2\x02\"RoadRunner\\Jobs\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_jobs_v2_request_proto_rawDescOnce sync.Once
	file_jobs_v2_request_proto_rawDescData []byte
)

func file_jobs_v2_request_proto_rawDescGZIP() []byte {
	file_jobs_v2_request_proto_rawDescOnce.Do(func() {
		file_jobs_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_v2_request_proto_rawDesc), len(file_jobs_v2_request_proto_rawDesc)))
	})
	return file_jobs_v2_request_proto_rawDescData
}

var file_jobs_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_jobs_v2_request_proto_goTypes = []any{
	(*JobsHandlerRequest)(nil), // 0: jobs.v2.JobsHandlerRequest
	(*PushBatchRequest)(nil),   // 1: jobs.v2.PushBatchRequest
	(*DeclareRequest)(nil),     // 2: jobs.v2.DeclareRequest
	nil,                        // 3: jobs.v2.PushBatchRequest.HeadersEntry
	nil,                        // 4: jobs.v2.DeclareRequest.PipelineEntry
	(*Job)(nil),                // 5: jobs.v2.Job
	(*JobHeaderValue)(nil),     // 6: jobs.v2.JobHeaderValue
}
var file_jobs_v2_request_proto_depIdxs = []int32{
	5, // 0: jobs.v2.JobsHandlerRequest.job:type_name -> jobs.v2.Job
	5, // 1: jobs.v2.PushBatchRequest.jobs:type_name -> jobs.v2.Job
	3, // 2: jobs.v2.PushBatchRequest.headers:type_name -> jobs.v2.PushBatchRequest.HeadersEntry
	4, // 3: jobs.v2.DeclareRequest.pipeline:type_name -> jobs.v2.DeclareRequest.PipelineEntry
	6, // 4: jobs.v2.PushBatchRequest.HeadersEntry.value:type_name -> jobs.v2.JobHeaderValue
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_jobs_v2_request_proto_init() }
func file_jobs_v2_request_proto_init() {
	if File_jobs_v2_request_proto != nil {
		return
	}
	file_jobs_v2_jobs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_v2_request_proto_rawDesc), len(file_jobs_v2_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jobs_v2_request_proto_goTypes,
		DependencyIndexes: file_jobs_v2_request_proto_depIdxs,
		MessageInfos:      file_jobs_v2_request_proto_msgTypes,
	}.Build()
	File_jobs_v2_request_proto = out.File
	file_jobs_v2_request_proto_goTypes = nil
	file_jobs_v2_request_proto_depIdxs = nil
}
