// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: jobs/v2/service.proto

package jobsV2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobsProxyService_JobsHandler_FullMethodName = "/jobs.v2.JobsProxyService/JobsHandler"
)

// JobsProxyServiceClient is the client API for JobsProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobsProxyServiceClient interface {
	JobsHandler(ctx context.Context, in *JobsHandlerRequest, opts ...grpc.CallOption) (*JobsHandlerResponse, error)
}

type jobsProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsProxyServiceClient(cc grpc.ClientConnInterface) JobsProxyServiceClient {
	return &jobsProxyServiceClient{cc}
}

func (c *jobsProxyServiceClient) JobsHandler(ctx context.Context, in *JobsHandlerRequest, opts ...grpc.CallOption) (*JobsHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsHandlerResponse)
	err := c.cc.Invoke(ctx, JobsProxyService_JobsHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobsProxyServiceServer is the server API for JobsProxyService service.
// All implementations must embed UnimplementedJobsProxyServiceServer
// for forward compatibility.
type JobsProxyServiceServer interface {
	JobsHandler(context.Context, *JobsHandlerRequest) (*JobsHandlerResponse, error)
	mustEmbedUnimplementedJobsProxyServiceServer()
}

// UnimplementedJobsProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobsProxyServiceServer struct{}

func (UnimplementedJobsProxyServiceServer) JobsHandler(context.Context, *JobsHandlerRequest) (*JobsHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobsHandler not implemented")
}
func (UnimplementedJobsProxyServiceServer) mustEmbedUnimplementedJobsProxyServiceServer() {}
func (UnimplementedJobsProxyServiceServer) testEmbeddedByValue()                          {}

// UnsafeJobsProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobsProxyServiceServer will
// result in compilation errors.
type UnsafeJobsProxyServiceServer interface {
	mustEmbedUnimplementedJobsProxyServiceServer()
}

func RegisterJobsProxyServiceServer(s grpc.ServiceRegistrar, srv JobsProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedJobsProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobsProxyService_ServiceDesc, srv)
}

func _JobsProxyService_JobsHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobsHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsProxyServiceServer).JobsHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsProxyService_JobsHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsProxyServiceServer).JobsHandler(ctx, req.(*JobsHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobsProxyService_ServiceDesc is the grpc.ServiceDesc for JobsProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobsProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobs.v2.JobsProxyService",
	HandlerType: (*JobsProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobsHandler",
			Handler:    _JobsProxyService_JobsHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobs/v2/service.proto",
}
