// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jobs/v2/service.proto

package jobsV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_jobs_v2_service_proto protoreflect.FileDescriptor

const file_jobs_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x15jobs/v2/service.proto\x12\ajobs.v2\x1a\x15jobs/v2/request.proto\x1a\x16jobs/v2/response.proto2\\\n" +
	"\x10JobsProxyService\x12H\n" +
	"\vJobsHandler\x12\x1b.jobs.v2.JobsHandlerRequest\x1a\x1c.jobs.v2.JobsHandlerResponseBuZ5github.com/roadrunner-server/api-go/v6/jobs/v2;jobsV2\xca\x02\x16RoadRunner\\Jobs\\DTO\\V2\xe2\x02\"RoadRunner\\Jobs\\DTO\\V2\\GPBMetadatab\x06proto3"

var file_jobs_v2_service_proto_goTypes = []any{
	(*JobsHandlerRequest)(nil),  // 0: jobs.v2.JobsHandlerRequest
	(*JobsHandlerResponse)(nil), // 1: jobs.v2.JobsHandlerResponse
}
var file_jobs_v2_service_proto_depIdxs = []int32{
	0, // 0: jobs.v2.JobsProxyService.JobsHandler:input_type -> jobs.v2.JobsHandlerRequest
	1, // 1: jobs.v2.JobsProxyService.JobsHandler:output_type -> jobs.v2.JobsHandlerResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jobs_v2_service_proto_init() }
func file_jobs_v2_service_proto_init() {
	if File_jobs_v2_service_proto != nil {
		return
	}
	file_jobs_v2_request_proto_init()
	file_jobs_v2_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_v2_service_proto_rawDesc), len(file_jobs_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobs_v2_service_proto_goTypes,
		DependencyIndexes: file_jobs_v2_service_proto_depIdxs,
	}.Build()
	File_jobs_v2_service_proto = out.File
	file_jobs_v2_service_proto_goTypes = nil
	file_jobs_v2_service_proto_depIdxs = nil
}
