// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: temporal/v1/service.proto

package temporalV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecordHeartbeatRequest is sent by an activity to record its current progress.
type RecordHeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// value of the binary "TaskToken" field of the "ActivityInfo" struct
	// retrieved inside the activity
	TaskToken []byte `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	// progress recorded along with the heartbeat
	Details       []byte `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordHeartbeatRequest) Reset() {
	*x = RecordHeartbeatRequest{}
	mi := &file_temporal_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHeartbeatRequest) ProtoMessage() {}

func (x *RecordHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RecordHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *RecordHeartbeatRequest) GetTaskToken() []byte {
	if x != nil {
		return x.TaskToken
	}
	return nil
}

func (x *RecordHeartbeatRequest) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type RecordHeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the activity was requested to cancel
	Canceled bool `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	// the activity was paused
	Paused        bool `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordHeartbeatResponse) Reset() {
	*x = RecordHeartbeatResponse{}
	mi := &file_temporal_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHeartbeatResponse) ProtoMessage() {}

func (x *RecordHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RecordHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecordHeartbeatResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *RecordHeartbeatResponse) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type GetNamesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNamesRequest) Reset() {
	*x = GetNamesRequest{}
	mi := &file_temporal_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamesRequest) ProtoMessage() {}

func (x *GetNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamesRequest.ProtoReflect.Descriptor instead.
func (*GetNamesRequest) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{2}
}

type NamesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamesList) Reset() {
	*x = NamesList{}
	mi := &file_temporal_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamesList) ProtoMessage() {}

func (x *NamesList) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamesList.ProtoReflect.Descriptor instead.
func (*NamesList) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *NamesList) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type UpdateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAPIKeyRequest) Reset() {
	*x = UpdateAPIKeyRequest{}
	mi := &file_temporal_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPIKeyRequest) ProtoMessage() {}

func (x *UpdateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type UpdateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAPIKeyResponse) Reset() {
	*x = UpdateAPIKeyResponse{}
	mi := &file_temporal_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAPIKeyResponse) ProtoMessage() {}

func (x *UpdateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*UpdateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_temporal_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAPIKeyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_temporal_v1_service_proto protoreflect.FileDescriptor

const file_temporal_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19temporal/v1/service.proto\x12\vtemporal.v1\x1a\x1atemporal/v1/temporal.proto\"Q\n" +
	"\x16RecordHeartbeatRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\fR\ttaskToken\x12\x18\n" +
	"\adetails\x18\x02 \x01(\fR\adetails\"M\n" +
	"\x17RecordHeartbeatResponse\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\"\x11\n" +
	"\x0fGetNamesRequest\"!\n" +
	"\tNamesList\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\".\n" +
	"\x13UpdateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"&\n" +
	"\x14UpdateAPIKeyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xa0\x05\n" +
	"\x0fTemporalService\x12d\n" +
	"\x17RecordActivityHeartbeat\x12#.temporal.v1.RecordHeartbeatRequest\x1a$.temporal.v1.RecordHeartbeatResponse\x12M\n" +
	"\x10GetActivityNames\x12\x1c.temporal.v1.GetNamesRequest\x1a\x16.temporal.v1.NamesList\"\x03\x90\x02\x01\x12M\n" +
	"\x10GetWorkflowNames\x12\x1c.temporal.v1.GetNamesRequest\x1a\x16.temporal.v1.NamesList\"\x03\x90\x02\x01\x12I\n" +
	"\x0eReplayWorkflow\x12\x1a.temporal.v1.ReplayRequest\x1a\x1b.temporal.v1.ReplayResponse\x12R\n" +
	"\x17DownloadWorkflowHistory\x12\x1a.temporal.v1.ReplayRequest\x1a\x1b.temporal.v1.ReplayResponse\x12I\n" +
	"\x0eReplayFromJSON\x12\x1a.temporal.v1.ReplayRequest\x1a\x1b.temporal.v1.ReplayResponse\x12J\n" +
	"\x15ReplayWorkflowHistory\x12\x14.temporal.v1.History\x1a\x1b.temporal.v1.ReplayResponse\x12S\n" +
	"\fUpdateAPIKey\x12 .temporal.v1.UpdateAPIKeyRequest\x1a!.temporal.v1.UpdateAPIKeyResponseB\x85\x01Z=github.com/roadrunner-server/api-go/v6/temporal/v1;temporalV1\xca\x02\x1aRoadRunner\\Temporal\\DTO\\V1\xe2\x02&RoadRunner\\Temporal\\DTO\\V1\\GPBMetadatab\x06proto3"

var (
	file_temporal_v1_service_proto_rawDescOnce sync.Once
	file_temporal_v1_service_proto_rawDescData []byte
)

func file_temporal_v1_service_proto_rawDescGZIP() []byte {
	file_temporal_v1_service_proto_rawDescOnce.Do(func() {
		file_temporal_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_v1_service_proto_rawDesc), len(file_temporal_v1_service_proto_rawDesc)))
	})
	return file_temporal_v1_service_proto_rawDescData
}

var file_temporal_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_temporal_v1_service_proto_goTypes = []any{
	(*RecordHeartbeatRequest)(nil),  // 0: temporal.v1.RecordHeartbeatRequest
	(*RecordHeartbeatResponse)(nil), // 1: temporal.v1.RecordHeartbeatResponse
	(*GetNamesRequest)(nil),         // 2: temporal.v1.GetNamesRequest
	(*NamesList)(nil),               // 3: temporal.v1.NamesList
	(*UpdateAPIKeyRequest)(nil),     // 4: temporal.v1.UpdateAPIKeyRequest
	(*UpdateAPIKeyResponse)(nil),    // 5: temporal.v1.UpdateAPIKeyResponse
	(*ReplayRequest)(nil),           // 6: temporal.v1.ReplayRequest
	(*History)(nil),                 // 7: temporal.v1.History
	(*ReplayResponse)(nil),          // 8: temporal.v1.ReplayResponse
}
var file_temporal_v1_service_proto_depIdxs = []int32{
	0, // 0: temporal.v1.TemporalService.RecordActivityHeartbeat:input_type -> temporal.v1.RecordHeartbeatRequest
	2, // 1: temporal.v1.TemporalService.GetActivityNames:input_type -> temporal.v1.GetNamesRequest
	2, // 2: temporal.v1.TemporalService.GetWorkflowNames:input_type -> temporal.v1.GetNamesRequest
	6, // 3: temporal.v1.TemporalService.ReplayWorkflow:input_type -> temporal.v1.ReplayRequest
	6, // 4: temporal.v1.TemporalService.DownloadWorkflowHistory:input_type -> temporal.v1.ReplayRequest
	6, // 5: temporal.v1.TemporalService.ReplayFromJSON:input_type -> temporal.v1.ReplayRequest
	7, // 6: temporal.v1.TemporalService.ReplayWorkflowHistory:input_type -> temporal.v1.History
	4, // 7: temporal.v1.TemporalService.UpdateAPIKey:input_type -> temporal.v1.UpdateAPIKeyRequest
	1, // 8: temporal.v1.TemporalService.RecordActivityHeartbeat:output_type -> temporal.v1.RecordHeartbeatResponse
	3, // 9: temporal.v1.TemporalService.GetActivityNames:output_type -> temporal.v1.NamesList
	3, // 10: temporal.v1.TemporalService.GetWorkflowNames:output_type -> temporal.v1.NamesList
	8, // 11: temporal.v1.TemporalService.ReplayWorkflow:output_type -> temporal.v1.ReplayResponse
	8, // 12: temporal.v1.TemporalService.DownloadWorkflowHistory:output_type -> temporal.v1.ReplayResponse
	8, // 13: temporal.v1.TemporalService.ReplayFromJSON:output_type -> temporal.v1.ReplayResponse
	8, // 14: temporal.v1.TemporalService.ReplayWorkflowHistory:output_type -> temporal.v1.ReplayResponse
	5, // 15: temporal.v1.TemporalService.UpdateAPIKey:output_type -> temporal.v1.UpdateAPIKeyResponse
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temporal_v1_service_proto_init() }
func file_temporal_v1_service_proto_init() {
	if File_temporal_v1_service_proto != nil {
		return
	}
	file_temporal_v1_temporal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_v1_service_proto_rawDesc), len(file_temporal_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_temporal_v1_service_proto_goTypes,
		DependencyIndexes: file_temporal_v1_service_proto_depIdxs,
		MessageInfos:      file_temporal_v1_service_proto_msgTypes,
	}.Build()
	File_temporal_v1_service_proto = out.File
	file_temporal_v1_service_proto_goTypes = nil
	file_temporal_v1_service_proto_depIdxs = nil
}
