// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: temporal/v1/service.proto

package temporalV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemporalService_RecordActivityHeartbeat_FullMethodName = "/temporal.v1.TemporalService/RecordActivityHeartbeat"
	TemporalService_GetActivityNames_FullMethodName        = "/temporal.v1.TemporalService/GetActivityNames"
	TemporalService_GetWorkflowNames_FullMethodName        = "/temporal.v1.TemporalService/GetWorkflowNames"
	TemporalService_ReplayWorkflow_FullMethodName          = "/temporal.v1.TemporalService/ReplayWorkflow"
	TemporalService_DownloadWorkflowHistory_FullMethodName = "/temporal.v1.TemporalService/DownloadWorkflowHistory"
	TemporalService_ReplayFromJSON_FullMethodName          = "/temporal.v1.TemporalService/ReplayFromJSON"
	TemporalService_ReplayWorkflowHistory_FullMethodName   = "/temporal.v1.TemporalService/ReplayWorkflowHistory"
	TemporalService_UpdateAPIKey_FullMethodName            = "/temporal.v1.TemporalService/UpdateAPIKey"
)

// TemporalServiceClient is the client API for TemporalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TemporalService exposes the temporal plugin control RPCs: activity
// heartbeats, registered workflow/activity introspection, workflow replay
// tooling, and API key rotation.
type TemporalServiceClient interface {
	RecordActivityHeartbeat(ctx context.Context, in *RecordHeartbeatRequest, opts ...grpc.CallOption) (*RecordHeartbeatResponse, error)
	GetActivityNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*NamesList, error)
	GetWorkflowNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*NamesList, error)
	ReplayWorkflow(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
	DownloadWorkflowHistory(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
	ReplayFromJSON(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error)
	ReplayWorkflowHistory(ctx context.Context, in *History, opts ...grpc.CallOption) (*ReplayResponse, error)
	UpdateAPIKey(ctx context.Context, in *UpdateAPIKeyRequest, opts ...grpc.CallOption) (*UpdateAPIKeyResponse, error)
}

type temporalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemporalServiceClient(cc grpc.ClientConnInterface) TemporalServiceClient {
	return &temporalServiceClient{cc}
}

func (c *temporalServiceClient) RecordActivityHeartbeat(ctx context.Context, in *RecordHeartbeatRequest, opts ...grpc.CallOption) (*RecordHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordHeartbeatResponse)
	err := c.cc.Invoke(ctx, TemporalService_RecordActivityHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) GetActivityNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*NamesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamesList)
	err := c.cc.Invoke(ctx, TemporalService_GetActivityNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) GetWorkflowNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*NamesList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamesList)
	err := c.cc.Invoke(ctx, TemporalService_GetWorkflowNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) ReplayWorkflow(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, TemporalService_ReplayWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) DownloadWorkflowHistory(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, TemporalService_DownloadWorkflowHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) ReplayFromJSON(ctx context.Context, in *ReplayRequest, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, TemporalService_ReplayFromJSON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) ReplayWorkflowHistory(ctx context.Context, in *History, opts ...grpc.CallOption) (*ReplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayResponse)
	err := c.cc.Invoke(ctx, TemporalService_ReplayWorkflowHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *temporalServiceClient) UpdateAPIKey(ctx context.Context, in *UpdateAPIKeyRequest, opts ...grpc.CallOption) (*UpdateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAPIKeyResponse)
	err := c.cc.Invoke(ctx, TemporalService_UpdateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemporalServiceServer is the server API for TemporalService service.
// All implementations must embed UnimplementedTemporalServiceServer
// for forward compatibility.
//
// TemporalService exposes the temporal plugin control RPCs: activity
// heartbeats, registered workflow/activity introspection, workflow replay
// tooling, and API key rotation.
type TemporalServiceServer interface {
	RecordActivityHeartbeat(context.Context, *RecordHeartbeatRequest) (*RecordHeartbeatResponse, error)
	GetActivityNames(context.Context, *GetNamesRequest) (*NamesList, error)
	GetWorkflowNames(context.Context, *GetNamesRequest) (*NamesList, error)
	ReplayWorkflow(context.Context, *ReplayRequest) (*ReplayResponse, error)
	DownloadWorkflowHistory(context.Context, *ReplayRequest) (*ReplayResponse, error)
	ReplayFromJSON(context.Context, *ReplayRequest) (*ReplayResponse, error)
	ReplayWorkflowHistory(context.Context, *History) (*ReplayResponse, error)
	UpdateAPIKey(context.Context, *UpdateAPIKeyRequest) (*UpdateAPIKeyResponse, error)
	mustEmbedUnimplementedTemporalServiceServer()
}

// UnimplementedTemporalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemporalServiceServer struct{}

func (UnimplementedTemporalServiceServer) RecordActivityHeartbeat(context.Context, *RecordHeartbeatRequest) (*RecordHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordActivityHeartbeat not implemented")
}
func (UnimplementedTemporalServiceServer) GetActivityNames(context.Context, *GetNamesRequest) (*NamesList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivityNames not implemented")
}
func (UnimplementedTemporalServiceServer) GetWorkflowNames(context.Context, *GetNamesRequest) (*NamesList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowNames not implemented")
}
func (UnimplementedTemporalServiceServer) ReplayWorkflow(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayWorkflow not implemented")
}
func (UnimplementedTemporalServiceServer) DownloadWorkflowHistory(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadWorkflowHistory not implemented")
}
func (UnimplementedTemporalServiceServer) ReplayFromJSON(context.Context, *ReplayRequest) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayFromJSON not implemented")
}
func (UnimplementedTemporalServiceServer) ReplayWorkflowHistory(context.Context, *History) (*ReplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayWorkflowHistory not implemented")
}
func (UnimplementedTemporalServiceServer) UpdateAPIKey(context.Context, *UpdateAPIKeyRequest) (*UpdateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAPIKey not implemented")
}
func (UnimplementedTemporalServiceServer) mustEmbedUnimplementedTemporalServiceServer() {}
func (UnimplementedTemporalServiceServer) testEmbeddedByValue()                         {}

// UnsafeTemporalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemporalServiceServer will
// result in compilation errors.
type UnsafeTemporalServiceServer interface {
	mustEmbedUnimplementedTemporalServiceServer()
}

func RegisterTemporalServiceServer(s grpc.ServiceRegistrar, srv TemporalServiceServer) {
	// If the following call panics, it indicates UnimplementedTemporalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemporalService_ServiceDesc, srv)
}

func _TemporalService_RecordActivityHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).RecordActivityHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_RecordActivityHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).RecordActivityHeartbeat(ctx, req.(*RecordHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_GetActivityNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).GetActivityNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_GetActivityNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).GetActivityNames(ctx, req.(*GetNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_GetWorkflowNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).GetWorkflowNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_GetWorkflowNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).GetWorkflowNames(ctx, req.(*GetNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_ReplayWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).ReplayWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_ReplayWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).ReplayWorkflow(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_DownloadWorkflowHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).DownloadWorkflowHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_DownloadWorkflowHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).DownloadWorkflowHistory(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_ReplayFromJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).ReplayFromJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_ReplayFromJSON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).ReplayFromJSON(ctx, req.(*ReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_ReplayWorkflowHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(History)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).ReplayWorkflowHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_ReplayWorkflowHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).ReplayWorkflowHistory(ctx, req.(*History))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemporalService_UpdateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemporalServiceServer).UpdateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemporalService_UpdateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemporalServiceServer).UpdateAPIKey(ctx, req.(*UpdateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemporalService_ServiceDesc is the grpc.ServiceDesc for TemporalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemporalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.v1.TemporalService",
	HandlerType: (*TemporalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordActivityHeartbeat",
			Handler:    _TemporalService_RecordActivityHeartbeat_Handler,
		},
		{
			MethodName: "GetActivityNames",
			Handler:    _TemporalService_GetActivityNames_Handler,
		},
		{
			MethodName: "GetWorkflowNames",
			Handler:    _TemporalService_GetWorkflowNames_Handler,
		},
		{
			MethodName: "ReplayWorkflow",
			Handler:    _TemporalService_ReplayWorkflow_Handler,
		},
		{
			MethodName: "DownloadWorkflowHistory",
			Handler:    _TemporalService_DownloadWorkflowHistory_Handler,
		},
		{
			MethodName: "ReplayFromJSON",
			Handler:    _TemporalService_ReplayFromJSON_Handler,
		},
		{
			MethodName: "ReplayWorkflowHistory",
			Handler:    _TemporalService_ReplayWorkflowHistory_Handler,
		},
		{
			MethodName: "UpdateAPIKey",
			Handler:    _TemporalService_UpdateAPIKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/v1/service.proto",
}
