// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: http/v2/http.proto

package httpV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpHeader struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Header        map[string]*HttpHeaderValue `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	mi := &file_http_v2_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_http_v2_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeader.ProtoReflect.Descriptor instead.
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return file_http_v2_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpHeader) GetHeader() map[string]*HttpHeaderValue {
	if x != nil {
		return x.Header
	}
	return nil
}

type HttpHeaderValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeaderValue) Reset() {
	*x = HttpHeaderValue{}
	mi := &file_http_v2_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeaderValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeaderValue) ProtoMessage() {}

func (x *HttpHeaderValue) ProtoReflect() protoreflect.Message {
	mi := &file_http_v2_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeaderValue.ProtoReflect.Descriptor instead.
func (*HttpHeaderValue) Descriptor() ([]byte, []int) {
	return file_http_v2_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpHeaderValue) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_http_v2_http_proto protoreflect.FileDescriptor

const file_http_v2_http_proto_rawDesc = "" +
	"\n" +
	"\x12http/v2/http.proto\x12\ahttp.v2\"\x9a\x01\n" +
	"\n" +
	"HttpHeader\x127\n" +
	"\x06header\x18\x01 \x03(\v2\x1f.http.v2.HttpHeader.HeaderEntryR\x06header\x1aS\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\")\n" +
	"\x0fHttpHeaderValue\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06valuesBuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xca\x02\x16RoadRunner\\HTTP\\DTO\\V2\xe2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_http_v2_http_proto_rawDescOnce sync.Once
	file_http_v2_http_proto_rawDescData []byte
)

func file_http_v2_http_proto_rawDescGZIP() []byte {
	file_http_v2_http_proto_rawDescOnce.Do(func() {
		file_http_v2_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_v2_http_proto_rawDesc), len(file_http_v2_http_proto_rawDesc)))
	})
	return file_http_v2_http_proto_rawDescData
}

var file_http_v2_http_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_http_v2_http_proto_goTypes = []any{
	(*HttpHeader)(nil),      // 0: http.v2.HttpHeader
	(*HttpHeaderValue)(nil), // 1: http.v2.HttpHeaderValue
	nil,                     // 2: http.v2.HttpHeader.HeaderEntry
}
var file_http_v2_http_proto_depIdxs = []int32{
	2, // 0: http.v2.HttpHeader.header:type_name -> http.v2.HttpHeader.HeaderEntry
	1, // 1: http.v2.HttpHeader.HeaderEntry.value:type_name -> http.v2.HttpHeaderValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_http_v2_http_proto_init() }
func file_http_v2_http_proto_init() {
	if File_http_v2_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_v2_http_proto_rawDesc), len(file_http_v2_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_v2_http_proto_goTypes,
		DependencyIndexes: file_http_v2_http_proto_depIdxs,
		MessageInfos:      file_http_v2_http_proto_msgTypes,
	}.Build()
	File_http_v2_http_proto = out.File
	file_http_v2_http_proto_goTypes = nil
	file_http_v2_http_proto_depIdxs = nil
}
