// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: http/v2/request.proto

package httpV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpHandlerRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	RemoteAddr    string                      `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Protocol      string                      `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method        string                      `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Uri           string                      `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Header        map[string]*HttpHeaderValue `protobuf:"bytes,5,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cookies       map[string]*HttpHeaderValue `protobuf:"bytes,6,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RawQuery      string                      `protobuf:"bytes,7,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Parsed        bool                        `protobuf:"varint,8,opt,name=parsed,proto3" json:"parsed,omitempty"`
	Uploads       []byte                      `protobuf:"bytes,9,opt,name=uploads,proto3" json:"uploads,omitempty"`
	Attributes    map[string]*HttpHeaderValue `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHandlerRequest) Reset() {
	*x = HttpHandlerRequest{}
	mi := &file_http_v2_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHandlerRequest) ProtoMessage() {}

func (x *HttpHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_http_v2_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHandlerRequest.ProtoReflect.Descriptor instead.
func (*HttpHandlerRequest) Descriptor() ([]byte, []int) {
	return file_http_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *HttpHandlerRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *HttpHandlerRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *HttpHandlerRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpHandlerRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *HttpHandlerRequest) GetHeader() map[string]*HttpHeaderValue {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HttpHandlerRequest) GetCookies() map[string]*HttpHeaderValue {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *HttpHandlerRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HttpHandlerRequest) GetParsed() bool {
	if x != nil {
		return x.Parsed
	}
	return false
}

func (x *HttpHandlerRequest) GetUploads() []byte {
	if x != nil {
		return x.Uploads
	}
	return nil
}

func (x *HttpHandlerRequest) GetAttributes() map[string]*HttpHeaderValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_http_v2_request_proto protoreflect.FileDescriptor

const file_http_v2_request_proto_rawDesc = "" +
	"\n" +
	"\x15http/v2/request.proto\x12\ahttp.v2\x1a\x12http/v2/http.proto\"\xa0\x05\n" +
	"\x12HttpHandlerRequest\x12\x1f\n" +
	"\vremote_addr\x18\x01 \x01(\tR\n" +
	"remoteAddr\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\x12?\n" +
	"\x06header\x18\x05 \x03(\v2'.http.v2.HttpHandlerRequest.HeaderEntryR\x06header\x12B\n" +
	"\acookies\x18\x06 \x03(\v2(.http.v2.HttpHandlerRequest.CookiesEntryR\acookies\x12\x1b\n" +
	"\traw_query\x18\a \x01(\tR\brawQuery\x12\x16\n" +
	"\x06parsed\x18\b \x01(\bR\x06parsed\x12\x18\n" +
	"\auploads\x18\t \x01(\fR\auploads\x12K\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2+.http.v2.HttpHandlerRequest.AttributesEntryR\n" +
	"attributes\x1aS\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\x1aT\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01\x1aW\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.http.v2.HttpHeaderValueR\x05value:\x028\x01BuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xca\x02\x16RoadRunner\\HTTP\\DTO\\V2\xe2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_http_v2_request_proto_rawDescOnce sync.Once
	file_http_v2_request_proto_rawDescData []byte
)

func file_http_v2_request_proto_rawDescGZIP() []byte {
	file_http_v2_request_proto_rawDescOnce.Do(func() {
		file_http_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_http_v2_request_proto_rawDesc), len(file_http_v2_request_proto_rawDesc)))
	})
	return file_http_v2_request_proto_rawDescData
}

var file_http_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_http_v2_request_proto_goTypes = []any{
	(*HttpHandlerRequest)(nil), // 0: http.v2.HttpHandlerRequest
	nil,                        // 1: http.v2.HttpHandlerRequest.HeaderEntry
	nil,                        // 2: http.v2.HttpHandlerRequest.CookiesEntry
	nil,                        // 3: http.v2.HttpHandlerRequest.AttributesEntry
	(*HttpHeaderValue)(nil),    // 4: http.v2.HttpHeaderValue
}
var file_http_v2_request_proto_depIdxs = []int32{
	1, // 0: http.v2.HttpHandlerRequest.header:type_name -> http.v2.HttpHandlerRequest.HeaderEntry
	2, // 1: http.v2.HttpHandlerRequest.cookies:type_name -> http.v2.HttpHandlerRequest.CookiesEntry
	3, // 2: http.v2.HttpHandlerRequest.attributes:type_name -> http.v2.HttpHandlerRequest.AttributesEntry
	4, // 3: http.v2.HttpHandlerRequest.HeaderEntry.value:type_name -> http.v2.HttpHeaderValue
	4, // 4: http.v2.HttpHandlerRequest.CookiesEntry.value:type_name -> http.v2.HttpHeaderValue
	4, // 5: http.v2.HttpHandlerRequest.AttributesEntry.value:type_name -> http.v2.HttpHeaderValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_http_v2_request_proto_init() }
func file_http_v2_request_proto_init() {
	if File_http_v2_request_proto != nil {
		return
	}
	file_http_v2_http_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_v2_request_proto_rawDesc), len(file_http_v2_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_http_v2_request_proto_goTypes,
		DependencyIndexes: file_http_v2_request_proto_depIdxs,
		MessageInfos:      file_http_v2_request_proto_msgTypes,
	}.Build()
	File_http_v2_request_proto = out.File
	file_http_v2_request_proto_goTypes = nil
	file_http_v2_request_proto_depIdxs = nil
}
