// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: http/v2/service.proto

package httpV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_http_v2_service_proto protoreflect.FileDescriptor

const file_http_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x15http/v2/service.proto\x12\ahttp.v2\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15http/v2/request.proto\x1a\x16http/v2/response.proto2\x80\x03\n" +
	"\x10HttpProxyService\x12C\n" +
	"\fFetchRequest\x12\x16.google.protobuf.Empty\x1a\x1b.http.v2.HttpHandlerRequest\x12F\n" +
	"\rStreamRequest\x12\x16.google.protobuf.Empty\x1a\x1b.http.v2.HttpHandlerRequest0\x01\x12O\n" +
	"\rFetchRequests\x12 .http.v2.HttpHandlerFetchRequest\x1a\x1c.http.v2.HttpHandlerRequests\x12D\n" +
	"\fSendResponse\x12\x1c.http.v2.HttpHandlerResponse\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eStreamResponse\x12\x1c.http.v2.HttpHandlerResponse\x1a\x16.google.protobuf.Empty(\x01BuZ5github.com/roadrunner-server/api-go/v6/http/v2;httpV2\xca\x02\x16RoadRunner\\HTTP\\DTO\\V2\xe2\x02\"RoadRunner\\HTTP\\DTO\\V2\\GPBMetadatab\x06proto3"

var file_http_v2_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),           // 0: google.protobuf.Empty
	(*HttpHandlerFetchRequest)(nil), // 1: http.v2.HttpHandlerFetchRequest
	(*HttpHandlerResponse)(nil),     // 2: http.v2.HttpHandlerResponse
	(*HttpHandlerRequest)(nil),      // 3: http.v2.HttpHandlerRequest
	(*HttpHandlerRequests)(nil),     // 4: http.v2.HttpHandlerRequests
}
var file_http_v2_service_proto_depIdxs = []int32{
	0, // 0: http.v2.HttpProxyService.FetchRequest:input_type -> google.protobuf.Empty
	0, // 1: http.v2.HttpProxyService.StreamRequest:input_type -> google.protobuf.Empty
	1, // 2: http.v2.HttpProxyService.FetchRequests:input_type -> http.v2.HttpHandlerFetchRequest
	2, // 3: http.v2.HttpProxyService.SendResponse:input_type -> http.v2.HttpHandlerResponse
	2, // 4: http.v2.HttpProxyService.StreamResponse:input_type -> http.v2.HttpHandlerResponse
	3, // 5: http.v2.HttpProxyService.FetchRequest:output_type -> http.v2.HttpHandlerRequest
	3, // 6: http.v2.HttpProxyService.StreamRequest:output_type -> http.v2.HttpHandlerRequest
	4, // 7: http.v2.HttpProxyService.FetchRequests:output_type -> http.v2.HttpHandlerRequests
	0, // 8: http.v2.HttpProxyService.SendResponse:output_type -> google.protobuf.Empty
	0, // 9: http.v2.HttpProxyService.StreamResponse:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_http_v2_service_proto_init() }
func file_http_v2_service_proto_init() {
	if File_http_v2_service_proto != nil {
		return
	}
	file_http_v2_request_proto_init()
	file_http_v2_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_http_v2_service_proto_rawDesc), len(file_http_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_http_v2_service_proto_goTypes,
		DependencyIndexes: file_http_v2_service_proto_depIdxs,
	}.Build()
	File_http_v2_service_proto = out.File
	file_http_v2_service_proto_goTypes = nil
	file_http_v2_service_proto_depIdxs = nil
}
