// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: http/v2/service.proto

package httpV2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HttpProxyService_FetchRequest_FullMethodName  = "/http.v2.HttpProxyService/FetchRequest"
	HttpProxyService_FetchRequests_FullMethodName = "/http.v2.HttpProxyService/FetchRequests"
	HttpProxyService_HttpHandler_FullMethodName   = "/http.v2.HttpProxyService/HttpHandler"
	HttpProxyService_HttpResponse_FullMethodName  = "/http.v2.HttpProxyService/HttpResponse"
)

// HttpProxyServiceClient is the client API for HttpProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpProxyServiceClient interface {
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	FetchRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HttpHandlerRequest, error)
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	FetchRequests(ctx context.Context, in *HttpHandlerFetchRequest, opts ...grpc.CallOption) (*HttpHandlerRequests, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	HttpHandler(ctx context.Context, in *HttpHandlerRequest, opts ...grpc.CallOption) (*HttpHandlerResponse, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	HttpResponse(ctx context.Context, in *HttpHandlerResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type httpProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpProxyServiceClient(cc grpc.ClientConnInterface) HttpProxyServiceClient {
	return &httpProxyServiceClient{cc}
}

func (c *httpProxyServiceClient) FetchRequest(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HttpHandlerRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpHandlerRequest)
	err := c.cc.Invoke(ctx, HttpProxyService_FetchRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpProxyServiceClient) FetchRequests(ctx context.Context, in *HttpHandlerFetchRequest, opts ...grpc.CallOption) (*HttpHandlerRequests, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpHandlerRequests)
	err := c.cc.Invoke(ctx, HttpProxyService_FetchRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpProxyServiceClient) HttpHandler(ctx context.Context, in *HttpHandlerRequest, opts ...grpc.CallOption) (*HttpHandlerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpHandlerResponse)
	err := c.cc.Invoke(ctx, HttpProxyService_HttpHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpProxyServiceClient) HttpResponse(ctx context.Context, in *HttpHandlerResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, HttpProxyService_HttpResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpProxyServiceServer is the server API for HttpProxyService service.
// All implementations must embed UnimplementedHttpProxyServiceServer
// for forward compatibility.
type HttpProxyServiceServer interface {
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	FetchRequest(context.Context, *emptypb.Empty) (*HttpHandlerRequest, error)
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	FetchRequests(context.Context, *HttpHandlerFetchRequest) (*HttpHandlerRequests, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	HttpHandler(context.Context, *HttpHandlerRequest) (*HttpHandlerResponse, error)
	// buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	HttpResponse(context.Context, *HttpHandlerResponse) (*emptypb.Empty, error)
	mustEmbedUnimplementedHttpProxyServiceServer()
}

// UnimplementedHttpProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpProxyServiceServer struct{}

func (UnimplementedHttpProxyServiceServer) FetchRequest(context.Context, *emptypb.Empty) (*HttpHandlerRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRequest not implemented")
}
func (UnimplementedHttpProxyServiceServer) FetchRequests(context.Context, *HttpHandlerFetchRequest) (*HttpHandlerRequests, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRequests not implemented")
}
func (UnimplementedHttpProxyServiceServer) HttpHandler(context.Context, *HttpHandlerRequest) (*HttpHandlerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HttpHandler not implemented")
}
func (UnimplementedHttpProxyServiceServer) HttpResponse(context.Context, *HttpHandlerResponse) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method HttpResponse not implemented")
}
func (UnimplementedHttpProxyServiceServer) mustEmbedUnimplementedHttpProxyServiceServer() {}
func (UnimplementedHttpProxyServiceServer) testEmbeddedByValue()                          {}

// UnsafeHttpProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpProxyServiceServer will
// result in compilation errors.
type UnsafeHttpProxyServiceServer interface {
	mustEmbedUnimplementedHttpProxyServiceServer()
}

func RegisterHttpProxyServiceServer(s grpc.ServiceRegistrar, srv HttpProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedHttpProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpProxyService_ServiceDesc, srv)
}

func _HttpProxyService_FetchRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpProxyServiceServer).FetchRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpProxyService_FetchRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpProxyServiceServer).FetchRequest(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpProxyService_FetchRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpHandlerFetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpProxyServiceServer).FetchRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpProxyService_FetchRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpProxyServiceServer).FetchRequests(ctx, req.(*HttpHandlerFetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpProxyService_HttpHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpHandlerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpProxyServiceServer).HttpHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpProxyService_HttpHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpProxyServiceServer).HttpHandler(ctx, req.(*HttpHandlerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpProxyService_HttpResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpHandlerResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpProxyServiceServer).HttpResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpProxyService_HttpResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpProxyServiceServer).HttpResponse(ctx, req.(*HttpHandlerResponse))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpProxyService_ServiceDesc is the grpc.ServiceDesc for HttpProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "http.v2.HttpProxyService",
	HandlerType: (*HttpProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchRequest",
			Handler:    _HttpProxyService_FetchRequest_Handler,
		},
		{
			MethodName: "FetchRequests",
			Handler:    _HttpProxyService_FetchRequests_Handler,
		},
		{
			MethodName: "HttpHandler",
			Handler:    _HttpProxyService_HttpHandler_Handler,
		},
		{
			MethodName: "HttpResponse",
			Handler:    _HttpProxyService_HttpResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "http/v2/service.proto",
}
