// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v2/request.proto

package serviceV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceCreateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command           string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ProcessNum        int64                  `protobuf:"varint,3,opt,name=process_num,json=processNum,proto3" json:"process_num,omitempty"`
	ExecTimeout       int64                  `protobuf:"varint,4,opt,name=exec_timeout,json=execTimeout,proto3" json:"exec_timeout,omitempty"`
	RemainAfterExit   bool                   `protobuf:"varint,5,opt,name=remain_after_exit,json=remainAfterExit,proto3" json:"remain_after_exit,omitempty"`
	Env               map[string]string      `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RestartSec        uint64                 `protobuf:"varint,7,opt,name=restart_sec,json=restartSec,proto3" json:"restart_sec,omitempty"`
	ServiceNameInLogs bool                   `protobuf:"varint,8,opt,name=service_name_in_logs,json=serviceNameInLogs,proto3" json:"service_name_in_logs,omitempty"`
	TimeoutStopSec    uint64                 `protobuf:"varint,9,opt,name=timeout_stop_sec,json=timeoutStopSec,proto3" json:"timeout_stop_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceCreateRequest) Reset() {
	*x = ServiceCreateRequest{}
	mi := &file_service_v2_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCreateRequest) ProtoMessage() {}

func (x *ServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v2_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_service_v2_request_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceCreateRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ServiceCreateRequest) GetProcessNum() int64 {
	if x != nil {
		return x.ProcessNum
	}
	return 0
}

func (x *ServiceCreateRequest) GetExecTimeout() int64 {
	if x != nil {
		return x.ExecTimeout
	}
	return 0
}

func (x *ServiceCreateRequest) GetRemainAfterExit() bool {
	if x != nil {
		return x.RemainAfterExit
	}
	return false
}

func (x *ServiceCreateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ServiceCreateRequest) GetRestartSec() uint64 {
	if x != nil {
		return x.RestartSec
	}
	return 0
}

func (x *ServiceCreateRequest) GetServiceNameInLogs() bool {
	if x != nil {
		return x.ServiceNameInLogs
	}
	return false
}

func (x *ServiceCreateRequest) GetTimeoutStopSec() uint64 {
	if x != nil {
		return x.TimeoutStopSec
	}
	return 0
}

type ServiceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfoRequest) Reset() {
	*x = ServiceInfoRequest{}
	mi := &file_service_v2_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoRequest) ProtoMessage() {}

func (x *ServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_v2_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*ServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_service_v2_request_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_service_v2_request_proto protoreflect.FileDescriptor

const file_service_v2_request_proto_rawDesc = "" +
	"\n" +
	"\x18service/v2/request.proto\x12\n" +
	"service.v2\"\xa5\x03\n" +
	"\x14ServiceCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x1f\n" +
	"\vprocess_num\x18\x03 \x01(\x03R\n" +
	"processNum\x12!\n" +
	"\fexec_timeout\x18\x04 \x01(\x03R\vexecTimeout\x12*\n" +
	"\x11remain_after_exit\x18\x05 \x01(\bR\x0fremainAfterExit\x12;\n" +
	"\x03env\x18\x06 \x03(\v2).service.v2.ServiceCreateRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vrestart_sec\x18\a \x01(\x04R\n" +
	"restartSec\x12/\n" +
	"\x14service_name_in_logs\x18\b \x01(\bR\x11serviceNameInLogs\x12(\n" +
	"\x10timeout_stop_sec\x18\t \x01(\x04R\x0etimeoutStopSec\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x12ServiceInfoRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v2;serviceV2\xca\x02\x19RoadRunner\\Service\\DTO\\V2\xe2\x02%RoadRunner\\Service\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_service_v2_request_proto_rawDescOnce sync.Once
	file_service_v2_request_proto_rawDescData []byte
)

func file_service_v2_request_proto_rawDescGZIP() []byte {
	file_service_v2_request_proto_rawDescOnce.Do(func() {
		file_service_v2_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v2_request_proto_rawDesc), len(file_service_v2_request_proto_rawDesc)))
	})
	return file_service_v2_request_proto_rawDescData
}

var file_service_v2_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_v2_request_proto_goTypes = []any{
	(*ServiceCreateRequest)(nil), // 0: service.v2.ServiceCreateRequest
	(*ServiceInfoRequest)(nil),   // 1: service.v2.ServiceInfoRequest
	nil,                          // 2: service.v2.ServiceCreateRequest.EnvEntry
}
var file_service_v2_request_proto_depIdxs = []int32{
	2, // 0: service.v2.ServiceCreateRequest.env:type_name -> service.v2.ServiceCreateRequest.EnvEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_v2_request_proto_init() }
func file_service_v2_request_proto_init() {
	if File_service_v2_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v2_request_proto_rawDesc), len(file_service_v2_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_v2_request_proto_goTypes,
		DependencyIndexes: file_service_v2_request_proto_depIdxs,
		MessageInfos:      file_service_v2_request_proto_msgTypes,
	}.Build()
	File_service_v2_request_proto = out.File
	file_service_v2_request_proto_goTypes = nil
	file_service_v2_request_proto_depIdxs = nil
}
