// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v2/response.proto

package serviceV2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	mi := &file_service_v2_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_v2_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_service_v2_response_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ServiceStatuses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ProcessStatus       `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceStatuses) Reset() {
	*x = ServiceStatuses{}
	mi := &file_service_v2_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatuses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatuses) ProtoMessage() {}

func (x *ServiceStatuses) ProtoReflect() protoreflect.Message {
	mi := &file_service_v2_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatuses.ProtoReflect.Descriptor instead.
func (*ServiceStatuses) Descriptor() ([]byte, []int) {
	return file_service_v2_response_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceStatuses) GetStatuses() []*ProcessStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ServiceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceList) Reset() {
	*x = ServiceList{}
	mi := &file_service_v2_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceList) ProtoMessage() {}

func (x *ServiceList) ProtoReflect() protoreflect.Message {
	mi := &file_service_v2_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceList.ProtoReflect.Descriptor instead.
func (*ServiceList) Descriptor() ([]byte, []int) {
	return file_service_v2_response_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceList) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_service_v2_response_proto protoreflect.FileDescriptor

const file_service_v2_response_proto_rawDesc = "" +
	"\n" +
	"\x19service/v2/response.proto\x12\n" +
	"service.v2\x1a\x18service/v2/service.proto\";\n" +
	"\x0fServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"H\n" +
	"\x0fServiceStatuses\x125\n" +
	"\bstatuses\x18\x01 \x03(\v2\x19.service.v2.ProcessStatusR\bstatuses\")\n" +
	"\vServiceList\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservicesB\x81\x01Z;github.com/roadrunner-server/api-go/v5/service/v2;serviceV2\xca\x02\x19RoadRunner\\Service\\DTO\\V2\xe2\x02%RoadRunner\\Service\\DTO\\V2\\GPBMetadatab\x06proto3"

var (
	file_service_v2_response_proto_rawDescOnce sync.Once
	file_service_v2_response_proto_rawDescData []byte
)

func file_service_v2_response_proto_rawDescGZIP() []byte {
	file_service_v2_response_proto_rawDescOnce.Do(func() {
		file_service_v2_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_v2_response_proto_rawDesc), len(file_service_v2_response_proto_rawDesc)))
	})
	return file_service_v2_response_proto_rawDescData
}

var file_service_v2_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_v2_response_proto_goTypes = []any{
	(*ServiceResponse)(nil), // 0: service.v2.ServiceResponse
	(*ServiceStatuses)(nil), // 1: service.v2.ServiceStatuses
	(*ServiceList)(nil),     // 2: service.v2.ServiceList
	(*ProcessStatus)(nil),   // 3: service.v2.ProcessStatus
}
var file_service_v2_response_proto_depIdxs = []int32{
	3, // 0: service.v2.ServiceStatuses.statuses:type_name -> service.v2.ProcessStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_v2_response_proto_init() }
func file_service_v2_response_proto_init() {
	if File_service_v2_response_proto != nil {
		return
	}
	file_service_v2_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v2_response_proto_rawDesc), len(file_service_v2_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_v2_response_proto_goTypes,
		DependencyIndexes: file_service_v2_response_proto_depIdxs,
		MessageInfos:      file_service_v2_response_proto_msgTypes,
	}.Build()
	File_service_v2_response_proto = out.File
	file_service_v2_response_proto_goTypes = nil
	file_service_v2_response_proto_depIdxs = nil
}
