// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: http/v2/service.proto

package httpV2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/roadrunner-server/api-go/v6/http/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HttpProxyServiceName is the fully-qualified name of the HttpProxyService service.
	HttpProxyServiceName = "http.v2.HttpProxyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HttpProxyServiceHttpHandlerProcedure is the fully-qualified name of the HttpProxyService's
	// HttpHandler RPC.
	HttpProxyServiceHttpHandlerProcedure = "/http.v2.HttpProxyService/HttpHandler"
)

// HttpProxyServiceClient is a client for the http.v2.HttpProxyService service.
type HttpProxyServiceClient interface {
	HttpHandler(context.Context, *connect.Request[v2.HttpHandlerRequest]) (*connect.Response[v2.HttpHandlerResponse], error)
}

// NewHttpProxyServiceClient constructs a client for the http.v2.HttpProxyService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHttpProxyServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HttpProxyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	httpProxyServiceMethods := v2.File_http_v2_service_proto.Services().ByName("HttpProxyService").Methods()
	return &httpProxyServiceClient{
		httpHandler: connect.NewClient[v2.HttpHandlerRequest, v2.HttpHandlerResponse](
			httpClient,
			baseURL+HttpProxyServiceHttpHandlerProcedure,
			connect.WithSchema(httpProxyServiceMethods.ByName("HttpHandler")),
			connect.WithClientOptions(opts...),
		),
	}
}

// httpProxyServiceClient implements HttpProxyServiceClient.
type httpProxyServiceClient struct {
	httpHandler *connect.Client[v2.HttpHandlerRequest, v2.HttpHandlerResponse]
}

// HttpHandler calls http.v2.HttpProxyService.HttpHandler.
func (c *httpProxyServiceClient) HttpHandler(ctx context.Context, req *connect.Request[v2.HttpHandlerRequest]) (*connect.Response[v2.HttpHandlerResponse], error) {
	return c.httpHandler.CallUnary(ctx, req)
}

// HttpProxyServiceHandler is an implementation of the http.v2.HttpProxyService service.
type HttpProxyServiceHandler interface {
	HttpHandler(context.Context, *connect.Request[v2.HttpHandlerRequest]) (*connect.Response[v2.HttpHandlerResponse], error)
}

// NewHttpProxyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHttpProxyServiceHandler(svc HttpProxyServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	httpProxyServiceMethods := v2.File_http_v2_service_proto.Services().ByName("HttpProxyService").Methods()
	httpProxyServiceHttpHandlerHandler := connect.NewUnaryHandler(
		HttpProxyServiceHttpHandlerProcedure,
		svc.HttpHandler,
		connect.WithSchema(httpProxyServiceMethods.ByName("HttpHandler")),
		connect.WithHandlerOptions(opts...),
	)
	return "/http.v2.HttpProxyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HttpProxyServiceHttpHandlerProcedure:
			httpProxyServiceHttpHandlerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHttpProxyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHttpProxyServiceHandler struct{}

func (UnimplementedHttpProxyServiceHandler) HttpHandler(context.Context, *connect.Request[v2.HttpHandlerRequest]) (*connect.Response[v2.HttpHandlerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("http.v2.HttpProxyService.HttpHandler is not implemented"))
}
