// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metrics/v1/service.proto

package metricsV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CollectorType enumerates the supported Prometheus collector kinds. The
// numeric values are stable; do not reuse or renumber.
type CollectorType int32

const (
	CollectorType_COLLECTOR_TYPE_UNSPECIFIED CollectorType = 0
	CollectorType_COLLECTOR_TYPE_HISTOGRAM   CollectorType = 1
	CollectorType_COLLECTOR_TYPE_GAUGE       CollectorType = 2
	CollectorType_COLLECTOR_TYPE_COUNTER     CollectorType = 3
	CollectorType_COLLECTOR_TYPE_SUMMARY     CollectorType = 4
)

// Enum value maps for CollectorType.
var (
	CollectorType_name = map[int32]string{
		0: "COLLECTOR_TYPE_UNSPECIFIED",
		1: "COLLECTOR_TYPE_HISTOGRAM",
		2: "COLLECTOR_TYPE_GAUGE",
		3: "COLLECTOR_TYPE_COUNTER",
		4: "COLLECTOR_TYPE_SUMMARY",
	}
	CollectorType_value = map[string]int32{
		"COLLECTOR_TYPE_UNSPECIFIED": 0,
		"COLLECTOR_TYPE_HISTOGRAM":   1,
		"COLLECTOR_TYPE_GAUGE":       2,
		"COLLECTOR_TYPE_COUNTER":     3,
		"COLLECTOR_TYPE_SUMMARY":     4,
	}
)

func (x CollectorType) Enum() *CollectorType {
	p := new(CollectorType)
	*p = x
	return p
}

func (x CollectorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectorType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_v1_service_proto_enumTypes[0].Descriptor()
}

func (CollectorType) Type() protoreflect.EnumType {
	return &file_metrics_v1_service_proto_enumTypes[0]
}

func (x CollectorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectorType.Descriptor instead.
func (CollectorType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{0}
}

// Objective is a single (quantile, error) pair for Prometheus summary
// collectors. proto3 forbids float-keyed maps, so summary objectives are
// modelled as a repeated message rather than `map<double, double>`.
type Objective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantile      float64                `protobuf:"fixed64,1,opt,name=quantile,proto3" json:"quantile,omitempty"`
	Error         float64                `protobuf:"fixed64,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objective) Reset() {
	*x = Objective{}
	mi := &file_metrics_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objective) ProtoMessage() {}

func (x *Objective) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objective.ProtoReflect.Descriptor instead.
func (*Objective) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Objective) GetQuantile() float64 {
	if x != nil {
		return x.Quantile
	}
	return 0
}

func (x *Objective) GetError() float64 {
	if x != nil {
		return x.Error
	}
	return 0
}

// Collector describes the shape of a single application-defined metric.
// Mirrors github.com/roadrunner-server/metrics/v6.Collector.
type Collector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem     string                 `protobuf:"bytes,2,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	Type          CollectorType          `protobuf:"varint,3,opt,name=type,proto3,enum=metrics.v1.CollectorType" json:"type,omitempty"`
	Help          string                 `protobuf:"bytes,4,opt,name=help,proto3" json:"help,omitempty"`
	Labels        []string               `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Buckets       []float64              `protobuf:"fixed64,6,rep,packed,name=buckets,proto3" json:"buckets,omitempty"`
	Objectives    []*Objective           `protobuf:"bytes,7,rep,name=objectives,proto3" json:"objectives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collector) Reset() {
	*x = Collector{}
	mi := &file_metrics_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collector) ProtoMessage() {}

func (x *Collector) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collector.ProtoReflect.Descriptor instead.
func (*Collector) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *Collector) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Collector) GetSubsystem() string {
	if x != nil {
		return x.Subsystem
	}
	return ""
}

func (x *Collector) GetType() CollectorType {
	if x != nil {
		return x.Type
	}
	return CollectorType_COLLECTOR_TYPE_UNSPECIFIED
}

func (x *Collector) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *Collector) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Collector) GetBuckets() []float64 {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *Collector) GetObjectives() []*Objective {
	if x != nil {
		return x.Objectives
	}
	return nil
}

// Metric is a single observation against an already-declared collector.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        []string               `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// NamedCollector wraps a Collector with its registry name; used only by
// Declare to register a new collector under that name.
type NamedCollector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Collector     *Collector             `protobuf:"bytes,2,opt,name=collector,proto3" json:"collector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedCollector) Reset() {
	*x = NamedCollector{}
	mi := &file_metrics_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedCollector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedCollector) ProtoMessage() {}

func (x *NamedCollector) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedCollector.ProtoReflect.Descriptor instead.
func (*NamedCollector) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *NamedCollector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedCollector) GetCollector() *Collector {
	if x != nil {
		return x.Collector
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type SubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type ObserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveRequest) Reset() {
	*x = ObserveRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveRequest) ProtoMessage() {}

func (x *ObserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveRequest.ProtoReflect.Descriptor instead.
func (*ObserveRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ObserveRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type DeclareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collector     *NamedCollector        `protobuf:"bytes,1,opt,name=collector,proto3" json:"collector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclareRequest) Reset() {
	*x = DeclareRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclareRequest) ProtoMessage() {}

func (x *DeclareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclareRequest.ProtoReflect.Descriptor instead.
func (*DeclareRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeclareRequest) GetCollector() *NamedCollector {
	if x != nil {
		return x.Collector
	}
	return nil
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_metrics_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnregisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_metrics_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_metrics_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_metrics_v1_service_proto protoreflect.FileDescriptor

const file_metrics_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18metrics/v1/service.proto\x12\n" +
	"metrics.v1\"=\n" +
	"\tObjective\x12\x1a\n" +
	"\bquantile\x18\x01 \x01(\x01R\bquantile\x12\x14\n" +
	"\x05error\x18\x02 \x01(\x01R\x05error\"\xf3\x01\n" +
	"\tCollector\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1c\n" +
	"\tsubsystem\x18\x02 \x01(\tR\tsubsystem\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.metrics.v1.CollectorTypeR\x04type\x12\x12\n" +
	"\x04help\x18\x04 \x01(\tR\x04help\x12\x16\n" +
	"\x06labels\x18\x05 \x03(\tR\x06labels\x12\x18\n" +
	"\abuckets\x18\x06 \x03(\x01R\abuckets\x125\n" +
	"\n" +
	"objectives\x18\a \x03(\v2\x15.metrics.v1.ObjectiveR\n" +
	"objectives\"J\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\"Y\n" +
	"\x0eNamedCollector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\tcollector\x18\x02 \x01(\v2\x15.metrics.v1.CollectorR\tcollector\"8\n" +
	"\n" +
	"AddRequest\x12*\n" +
	"\x06metric\x18\x01 \x01(\v2\x12.metrics.v1.MetricR\x06metric\"8\n" +
	"\n" +
	"SubRequest\x12*\n" +
	"\x06metric\x18\x01 \x01(\v2\x12.metrics.v1.MetricR\x06metric\"<\n" +
	"\x0eObserveRequest\x12*\n" +
	"\x06metric\x18\x01 \x01(\v2\x12.metrics.v1.MetricR\x06metric\"8\n" +
	"\n" +
	"SetRequest\x12*\n" +
	"\x06metric\x18\x01 \x01(\v2\x12.metrics.v1.MetricR\x06metric\"J\n" +
	"\x0eDeclareRequest\x128\n" +
	"\tcollector\x18\x01 \x01(\v2\x1a.metrics.v1.NamedCollectorR\tcollector\"'\n" +
	"\x11UnregisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\x9f\x01\n" +
	"\rCollectorType\x12\x1e\n" +
	"\x1aCOLLECTOR_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COLLECTOR_TYPE_HISTOGRAM\x10\x01\x12\x18\n" +
	"\x14COLLECTOR_TYPE_GAUGE\x10\x02\x12\x1a\n" +
	"\x16COLLECTOR_TYPE_COUNTER\x10\x03\x12\x1a\n" +
	"\x16COLLECTOR_TYPE_SUMMARY\x10\x042\xec\x02\n" +
	"\x0eMetricsService\x123\n" +
	"\x03Add\x12\x16.metrics.v1.AddRequest\x1a\x14.metrics.v1.Response\x123\n" +
	"\x03Sub\x12\x16.metrics.v1.SubRequest\x1a\x14.metrics.v1.Response\x12;\n" +
	"\aObserve\x12\x1a.metrics.v1.ObserveRequest\x1a\x14.metrics.v1.Response\x123\n" +
	"\x03Set\x12\x16.metrics.v1.SetRequest\x1a\x14.metrics.v1.Response\x12;\n" +
	"\aDeclare\x12\x1a.metrics.v1.DeclareRequest\x1a\x14.metrics.v1.Response\x12A\n" +
	"\n" +
	"Unregister\x12\x1d.metrics.v1.UnregisterRequest\x1a\x14.metrics.v1.ResponseB\x81\x01Z;github.com/roadrunner-server/api-go/v6/metrics/v1;metricsV1\xca\x02\x19RoadRunner\\Metrics\\DTO\\V1\xe2\x02%RoadRunner\\Metrics\\DTO\\V1\\GPBMetadatab\x06proto3"

var (
	file_metrics_v1_service_proto_rawDescOnce sync.Once
	file_metrics_v1_service_proto_rawDescData []byte
)

func file_metrics_v1_service_proto_rawDescGZIP() []byte {
	file_metrics_v1_service_proto_rawDescOnce.Do(func() {
		file_metrics_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_v1_service_proto_rawDesc), len(file_metrics_v1_service_proto_rawDesc)))
	})
	return file_metrics_v1_service_proto_rawDescData
}

var file_metrics_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metrics_v1_service_proto_goTypes = []any{
	(CollectorType)(0),        // 0: metrics.v1.CollectorType
	(*Objective)(nil),         // 1: metrics.v1.Objective
	(*Collector)(nil),         // 2: metrics.v1.Collector
	(*Metric)(nil),            // 3: metrics.v1.Metric
	(*NamedCollector)(nil),    // 4: metrics.v1.NamedCollector
	(*AddRequest)(nil),        // 5: metrics.v1.AddRequest
	(*SubRequest)(nil),        // 6: metrics.v1.SubRequest
	(*ObserveRequest)(nil),    // 7: metrics.v1.ObserveRequest
	(*SetRequest)(nil),        // 8: metrics.v1.SetRequest
	(*DeclareRequest)(nil),    // 9: metrics.v1.DeclareRequest
	(*UnregisterRequest)(nil), // 10: metrics.v1.UnregisterRequest
	(*Response)(nil),          // 11: metrics.v1.Response
}
var file_metrics_v1_service_proto_depIdxs = []int32{
	0,  // 0: metrics.v1.Collector.type:type_name -> metrics.v1.CollectorType
	1,  // 1: metrics.v1.Collector.objectives:type_name -> metrics.v1.Objective
	2,  // 2: metrics.v1.NamedCollector.collector:type_name -> metrics.v1.Collector
	3,  // 3: metrics.v1.AddRequest.metric:type_name -> metrics.v1.Metric
	3,  // 4: metrics.v1.SubRequest.metric:type_name -> metrics.v1.Metric
	3,  // 5: metrics.v1.ObserveRequest.metric:type_name -> metrics.v1.Metric
	3,  // 6: metrics.v1.SetRequest.metric:type_name -> metrics.v1.Metric
	4,  // 7: metrics.v1.DeclareRequest.collector:type_name -> metrics.v1.NamedCollector
	5,  // 8: metrics.v1.MetricsService.Add:input_type -> metrics.v1.AddRequest
	6,  // 9: metrics.v1.MetricsService.Sub:input_type -> metrics.v1.SubRequest
	7,  // 10: metrics.v1.MetricsService.Observe:input_type -> metrics.v1.ObserveRequest
	8,  // 11: metrics.v1.MetricsService.Set:input_type -> metrics.v1.SetRequest
	9,  // 12: metrics.v1.MetricsService.Declare:input_type -> metrics.v1.DeclareRequest
	10, // 13: metrics.v1.MetricsService.Unregister:input_type -> metrics.v1.UnregisterRequest
	11, // 14: metrics.v1.MetricsService.Add:output_type -> metrics.v1.Response
	11, // 15: metrics.v1.MetricsService.Sub:output_type -> metrics.v1.Response
	11, // 16: metrics.v1.MetricsService.Observe:output_type -> metrics.v1.Response
	11, // 17: metrics.v1.MetricsService.Set:output_type -> metrics.v1.Response
	11, // 18: metrics.v1.MetricsService.Declare:output_type -> metrics.v1.Response
	11, // 19: metrics.v1.MetricsService.Unregister:output_type -> metrics.v1.Response
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_metrics_v1_service_proto_init() }
func file_metrics_v1_service_proto_init() {
	if File_metrics_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_v1_service_proto_rawDesc), len(file_metrics_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_v1_service_proto_goTypes,
		DependencyIndexes: file_metrics_v1_service_proto_depIdxs,
		EnumInfos:         file_metrics_v1_service_proto_enumTypes,
		MessageInfos:      file_metrics_v1_service_proto_msgTypes,
	}.Build()
	File_metrics_v1_service_proto = out.File
	file_metrics_v1_service_proto_goTypes = nil
	file_metrics_v1_service_proto_depIdxs = nil
}
