// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service/v1/service_rpc.proto

package serviceV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_v1_service_rpc_proto protoreflect.FileDescriptor

const file_service_v1_service_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1cservice/v1/service_rpc.proto\x12\n" +
	"service.v1\x1a\x18service/v1/service.proto2\xe0\x02\n" +
	"\x0eServiceManager\x129\n" +
	"\rCreateService\x12\x12.service.v1.Create\x1a\x14.service.v1.Response\x126\n" +
	"\tTerminate\x12\x13.service.v1.Service\x1a\x14.service.v1.Response\x124\n" +
	"\aRestart\x12\x13.service.v1.Service\x1a\x14.service.v1.Response\x124\n" +
	"\tGetStatus\x12\x13.service.v1.Service\x1a\x12.service.v1.Status\x128\n" +
	"\vGetStatuses\x12\x13.service.v1.Service\x1a\x14.service.v1.Statuses\x125\n" +
	"\fListServices\x12\x13.service.v1.Service\x1a\x10.service.v1.ListB\x81\x01Z;github.com/roadrunner-server/api-go/v6/service/v1;serviceV1\xca\x02\x19RoadRunner\\Service\\DTO\\V1\xe2\x02%RoadRunner\\Service\\DTO\\V1\\GPBMetadatab\x06proto3"

var file_service_v1_service_rpc_proto_goTypes = []any{
	(*Create)(nil),   // 0: service.v1.Create
	(*Service)(nil),  // 1: service.v1.Service
	(*Response)(nil), // 2: service.v1.Response
	(*Status)(nil),   // 3: service.v1.Status
	(*Statuses)(nil), // 4: service.v1.Statuses
	(*List)(nil),     // 5: service.v1.List
}
var file_service_v1_service_rpc_proto_depIdxs = []int32{
	0, // 0: service.v1.ServiceManager.CreateService:input_type -> service.v1.Create
	1, // 1: service.v1.ServiceManager.Terminate:input_type -> service.v1.Service
	1, // 2: service.v1.ServiceManager.Restart:input_type -> service.v1.Service
	1, // 3: service.v1.ServiceManager.GetStatus:input_type -> service.v1.Service
	1, // 4: service.v1.ServiceManager.GetStatuses:input_type -> service.v1.Service
	1, // 5: service.v1.ServiceManager.ListServices:input_type -> service.v1.Service
	2, // 6: service.v1.ServiceManager.CreateService:output_type -> service.v1.Response
	2, // 7: service.v1.ServiceManager.Terminate:output_type -> service.v1.Response
	2, // 8: service.v1.ServiceManager.Restart:output_type -> service.v1.Response
	3, // 9: service.v1.ServiceManager.GetStatus:output_type -> service.v1.Status
	4, // 10: service.v1.ServiceManager.GetStatuses:output_type -> service.v1.Statuses
	5, // 11: service.v1.ServiceManager.ListServices:output_type -> service.v1.List
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_v1_service_rpc_proto_init() }
func file_service_v1_service_rpc_proto_init() {
	if File_service_v1_service_rpc_proto != nil {
		return
	}
	file_service_v1_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_v1_service_rpc_proto_rawDesc), len(file_service_v1_service_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_v1_service_rpc_proto_goTypes,
		DependencyIndexes: file_service_v1_service_rpc_proto_depIdxs,
	}.Build()
	File_service_v1_service_rpc_proto = out.File
	file_service_v1_service_rpc_proto_goTypes = nil
	file_service_v1_service_rpc_proto_depIdxs = nil
}
