// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: lock/v1/service.proto

package lockV1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/roadrunner-server/api-go/v6/lock/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LockServiceName is the fully-qualified name of the LockService service.
	LockServiceName = "lock.v1.LockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LockServiceLockProcedure is the fully-qualified name of the LockService's Lock RPC.
	LockServiceLockProcedure = "/lock.v1.LockService/Lock"
	// LockServiceLockReadProcedure is the fully-qualified name of the LockService's LockRead RPC.
	LockServiceLockReadProcedure = "/lock.v1.LockService/LockRead"
	// LockServiceReleaseProcedure is the fully-qualified name of the LockService's Release RPC.
	LockServiceReleaseProcedure = "/lock.v1.LockService/Release"
	// LockServiceForceReleaseProcedure is the fully-qualified name of the LockService's ForceRelease
	// RPC.
	LockServiceForceReleaseProcedure = "/lock.v1.LockService/ForceRelease"
	// LockServiceExistsProcedure is the fully-qualified name of the LockService's Exists RPC.
	LockServiceExistsProcedure = "/lock.v1.LockService/Exists"
	// LockServiceUpdateTTLProcedure is the fully-qualified name of the LockService's UpdateTTL RPC.
	LockServiceUpdateTTLProcedure = "/lock.v1.LockService/UpdateTTL"
)

// LockServiceClient is a client for the lock.v1.LockService service.
type LockServiceClient interface {
	Lock(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	LockRead(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	Release(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	ForceRelease(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	Exists(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	UpdateTTL(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
}

// NewLockServiceClient constructs a client for the lock.v1.LockService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLockServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	lockServiceMethods := v1.File_lock_v1_service_proto.Services().ByName("LockService").Methods()
	return &lockServiceClient{
		lock: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceLockProcedure,
			connect.WithSchema(lockServiceMethods.ByName("Lock")),
			connect.WithClientOptions(opts...),
		),
		lockRead: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceLockReadProcedure,
			connect.WithSchema(lockServiceMethods.ByName("LockRead")),
			connect.WithClientOptions(opts...),
		),
		release: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceReleaseProcedure,
			connect.WithSchema(lockServiceMethods.ByName("Release")),
			connect.WithClientOptions(opts...),
		),
		forceRelease: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceForceReleaseProcedure,
			connect.WithSchema(lockServiceMethods.ByName("ForceRelease")),
			connect.WithClientOptions(opts...),
		),
		exists: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceExistsProcedure,
			connect.WithSchema(lockServiceMethods.ByName("Exists")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateTTL: connect.NewClient[v1.LockRequest, v1.LockResponse](
			httpClient,
			baseURL+LockServiceUpdateTTLProcedure,
			connect.WithSchema(lockServiceMethods.ByName("UpdateTTL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// lockServiceClient implements LockServiceClient.
type lockServiceClient struct {
	lock         *connect.Client[v1.LockRequest, v1.LockResponse]
	lockRead     *connect.Client[v1.LockRequest, v1.LockResponse]
	release      *connect.Client[v1.LockRequest, v1.LockResponse]
	forceRelease *connect.Client[v1.LockRequest, v1.LockResponse]
	exists       *connect.Client[v1.LockRequest, v1.LockResponse]
	updateTTL    *connect.Client[v1.LockRequest, v1.LockResponse]
}

// Lock calls lock.v1.LockService.Lock.
func (c *lockServiceClient) Lock(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.lock.CallUnary(ctx, req)
}

// LockRead calls lock.v1.LockService.LockRead.
func (c *lockServiceClient) LockRead(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.lockRead.CallUnary(ctx, req)
}

// Release calls lock.v1.LockService.Release.
func (c *lockServiceClient) Release(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.release.CallUnary(ctx, req)
}

// ForceRelease calls lock.v1.LockService.ForceRelease.
func (c *lockServiceClient) ForceRelease(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.forceRelease.CallUnary(ctx, req)
}

// Exists calls lock.v1.LockService.Exists.
func (c *lockServiceClient) Exists(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.exists.CallUnary(ctx, req)
}

// UpdateTTL calls lock.v1.LockService.UpdateTTL.
func (c *lockServiceClient) UpdateTTL(ctx context.Context, req *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return c.updateTTL.CallUnary(ctx, req)
}

// LockServiceHandler is an implementation of the lock.v1.LockService service.
type LockServiceHandler interface {
	Lock(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	LockRead(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	Release(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	ForceRelease(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	Exists(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
	UpdateTTL(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error)
}

// NewLockServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLockServiceHandler(svc LockServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	lockServiceMethods := v1.File_lock_v1_service_proto.Services().ByName("LockService").Methods()
	lockServiceLockHandler := connect.NewUnaryHandler(
		LockServiceLockProcedure,
		svc.Lock,
		connect.WithSchema(lockServiceMethods.ByName("Lock")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceLockReadHandler := connect.NewUnaryHandler(
		LockServiceLockReadProcedure,
		svc.LockRead,
		connect.WithSchema(lockServiceMethods.ByName("LockRead")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceReleaseHandler := connect.NewUnaryHandler(
		LockServiceReleaseProcedure,
		svc.Release,
		connect.WithSchema(lockServiceMethods.ByName("Release")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceForceReleaseHandler := connect.NewUnaryHandler(
		LockServiceForceReleaseProcedure,
		svc.ForceRelease,
		connect.WithSchema(lockServiceMethods.ByName("ForceRelease")),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceExistsHandler := connect.NewUnaryHandler(
		LockServiceExistsProcedure,
		svc.Exists,
		connect.WithSchema(lockServiceMethods.ByName("Exists")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	lockServiceUpdateTTLHandler := connect.NewUnaryHandler(
		LockServiceUpdateTTLProcedure,
		svc.UpdateTTL,
		connect.WithSchema(lockServiceMethods.ByName("UpdateTTL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/lock.v1.LockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LockServiceLockProcedure:
			lockServiceLockHandler.ServeHTTP(w, r)
		case LockServiceLockReadProcedure:
			lockServiceLockReadHandler.ServeHTTP(w, r)
		case LockServiceReleaseProcedure:
			lockServiceReleaseHandler.ServeHTTP(w, r)
		case LockServiceForceReleaseProcedure:
			lockServiceForceReleaseHandler.ServeHTTP(w, r)
		case LockServiceExistsProcedure:
			lockServiceExistsHandler.ServeHTTP(w, r)
		case LockServiceUpdateTTLProcedure:
			lockServiceUpdateTTLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLockServiceHandler struct{}

func (UnimplementedLockServiceHandler) Lock(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.Lock is not implemented"))
}

func (UnimplementedLockServiceHandler) LockRead(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.LockRead is not implemented"))
}

func (UnimplementedLockServiceHandler) Release(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.Release is not implemented"))
}

func (UnimplementedLockServiceHandler) ForceRelease(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.ForceRelease is not implemented"))
}

func (UnimplementedLockServiceHandler) Exists(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.Exists is not implemented"))
}

func (UnimplementedLockServiceHandler) UpdateTTL(context.Context, *connect.Request[v1.LockRequest]) (*connect.Response[v1.LockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("lock.v1.LockService.UpdateTTL is not implemented"))
}
