// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: informer/v1/service.proto

package informerV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InformerService_ListPlugins_FullMethodName  = "/informer.v1.InformerService/ListPlugins"
	InformerService_GetWorkers_FullMethodName   = "/informer.v1.InformerService/GetWorkers"
	InformerService_GetJobs_FullMethodName      = "/informer.v1.InformerService/GetJobs"
	InformerService_AddWorker_FullMethodName    = "/informer.v1.InformerService/AddWorker"
	InformerService_RemoveWorker_FullMethodName = "/informer.v1.InformerService/RemoveWorker"
)

// InformerServiceClient is the client API for InformerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InformerService exposes introspection RPCs for plugins that manage workers
// (jobs, service, kv, etc.) and lets callers add or remove workers at runtime.
type InformerServiceClient interface {
	ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*PluginsList, error)
	GetWorkers(ctx context.Context, in *GetWorkersRequest, opts ...grpc.CallOption) (*WorkersList, error)
	GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*JobsList, error)
	AddWorker(ctx context.Context, in *AddWorkerRequest, opts ...grpc.CallOption) (*Response, error)
	RemoveWorker(ctx context.Context, in *RemoveWorkerRequest, opts ...grpc.CallOption) (*Response, error)
}

type informerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInformerServiceClient(cc grpc.ClientConnInterface) InformerServiceClient {
	return &informerServiceClient{cc}
}

func (c *informerServiceClient) ListPlugins(ctx context.Context, in *ListPluginsRequest, opts ...grpc.CallOption) (*PluginsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginsList)
	err := c.cc.Invoke(ctx, InformerService_ListPlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *informerServiceClient) GetWorkers(ctx context.Context, in *GetWorkersRequest, opts ...grpc.CallOption) (*WorkersList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkersList)
	err := c.cc.Invoke(ctx, InformerService_GetWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *informerServiceClient) GetJobs(ctx context.Context, in *GetJobsRequest, opts ...grpc.CallOption) (*JobsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobsList)
	err := c.cc.Invoke(ctx, InformerService_GetJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *informerServiceClient) AddWorker(ctx context.Context, in *AddWorkerRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, InformerService_AddWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *informerServiceClient) RemoveWorker(ctx context.Context, in *RemoveWorkerRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, InformerService_RemoveWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InformerServiceServer is the server API for InformerService service.
// All implementations must embed UnimplementedInformerServiceServer
// for forward compatibility.
//
// InformerService exposes introspection RPCs for plugins that manage workers
// (jobs, service, kv, etc.) and lets callers add or remove workers at runtime.
type InformerServiceServer interface {
	ListPlugins(context.Context, *ListPluginsRequest) (*PluginsList, error)
	GetWorkers(context.Context, *GetWorkersRequest) (*WorkersList, error)
	GetJobs(context.Context, *GetJobsRequest) (*JobsList, error)
	AddWorker(context.Context, *AddWorkerRequest) (*Response, error)
	RemoveWorker(context.Context, *RemoveWorkerRequest) (*Response, error)
	mustEmbedUnimplementedInformerServiceServer()
}

// UnimplementedInformerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInformerServiceServer struct{}

func (UnimplementedInformerServiceServer) ListPlugins(context.Context, *ListPluginsRequest) (*PluginsList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlugins not implemented")
}
func (UnimplementedInformerServiceServer) GetWorkers(context.Context, *GetWorkersRequest) (*WorkersList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkers not implemented")
}
func (UnimplementedInformerServiceServer) GetJobs(context.Context, *GetJobsRequest) (*JobsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobs not implemented")
}
func (UnimplementedInformerServiceServer) AddWorker(context.Context, *AddWorkerRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWorker not implemented")
}
func (UnimplementedInformerServiceServer) RemoveWorker(context.Context, *RemoveWorkerRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorker not implemented")
}
func (UnimplementedInformerServiceServer) mustEmbedUnimplementedInformerServiceServer() {}
func (UnimplementedInformerServiceServer) testEmbeddedByValue()                         {}

// UnsafeInformerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InformerServiceServer will
// result in compilation errors.
type UnsafeInformerServiceServer interface {
	mustEmbedUnimplementedInformerServiceServer()
}

func RegisterInformerServiceServer(s grpc.ServiceRegistrar, srv InformerServiceServer) {
	// If the following call panics, it indicates UnimplementedInformerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InformerService_ServiceDesc, srv)
}

func _InformerService_ListPlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformerServiceServer).ListPlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InformerService_ListPlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformerServiceServer).ListPlugins(ctx, req.(*ListPluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InformerService_GetWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformerServiceServer).GetWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InformerService_GetWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformerServiceServer).GetWorkers(ctx, req.(*GetWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InformerService_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformerServiceServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InformerService_GetJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformerServiceServer).GetJobs(ctx, req.(*GetJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InformerService_AddWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformerServiceServer).AddWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InformerService_AddWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformerServiceServer).AddWorker(ctx, req.(*AddWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InformerService_RemoveWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformerServiceServer).RemoveWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InformerService_RemoveWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformerServiceServer).RemoveWorker(ctx, req.(*RemoveWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InformerService_ServiceDesc is the grpc.ServiceDesc for InformerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InformerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "informer.v1.InformerService",
	HandlerType: (*InformerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlugins",
			Handler:    _InformerService_ListPlugins_Handler,
		},
		{
			MethodName: "GetWorkers",
			Handler:    _InformerService_GetWorkers_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _InformerService_GetJobs_Handler,
		},
		{
			MethodName: "AddWorker",
			Handler:    _InformerService_AddWorker_Handler,
		},
		{
			MethodName: "RemoveWorker",
			Handler:    _InformerService_RemoveWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "informer/v1/service.proto",
}
