// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: informer/v1/service.proto

package informerV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessState mirrors github.com/roadrunner-server/pool/v2/state/process.State —
// one entry per OS-level worker process managed by a plugin. Field widths match
// the existing service.v1.Status convention (int32 pid, float cpu_percent)
// rather than the Go-source int64/float64; PIDs fit in int32 per POSIX, and a
// percentage value comfortably fits in float32.
type ProcessState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	NumExecs      uint64                 `protobuf:"varint,3,opt,name=num_execs,json=numExecs,proto3" json:"num_execs,omitempty"`
	Created       int64                  `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	CpuPercent    float32                `protobuf:"fixed32,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	Command       string                 `protobuf:"bytes,7,opt,name=command,proto3" json:"command,omitempty"`
	StatusStr     string                 `protobuf:"bytes,8,opt,name=status_str,json=statusStr,proto3" json:"status_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessState) Reset() {
	*x = ProcessState{}
	mi := &file_informer_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessState) ProtoMessage() {}

func (x *ProcessState) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessState.ProtoReflect.Descriptor instead.
func (*ProcessState) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessState) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProcessState) GetNumExecs() uint64 {
	if x != nil {
		return x.NumExecs
	}
	return 0
}

func (x *ProcessState) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ProcessState) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ProcessState) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessState) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessState) GetStatusStr() string {
	if x != nil {
		return x.StatusStr
	}
	return ""
}

// JobState mirrors github.com/roadrunner-server/api-plugins/v6/jobs.State —
// one entry per consumer pipeline registered with the jobs plugin.
type JobState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      string                 `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Active        int64                  `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Delayed       int64                  `protobuf:"varint,5,opt,name=delayed,proto3" json:"delayed,omitempty"`
	Reserved      int64                  `protobuf:"varint,6,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Ready         bool                   `protobuf:"varint,7,opt,name=ready,proto3" json:"ready,omitempty"`
	Priority      uint64                 `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobState) Reset() {
	*x = JobState{}
	mi := &file_informer_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobState) ProtoMessage() {}

func (x *JobState) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobState.ProtoReflect.Descriptor instead.
func (*JobState) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *JobState) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *JobState) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *JobState) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobState) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *JobState) GetDelayed() int64 {
	if x != nil {
		return x.Delayed
	}
	return 0
}

func (x *JobState) GetReserved() int64 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *JobState) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *JobState) GetPriority() uint64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *JobState) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_informer_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{2}
}

type PluginsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []string               `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsList) Reset() {
	*x = PluginsList{}
	mi := &file_informer_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsList) ProtoMessage() {}

func (x *PluginsList) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsList.ProtoReflect.Descriptor instead.
func (*PluginsList) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *PluginsList) GetPlugins() []string {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type GetWorkersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkersRequest) Reset() {
	*x = GetWorkersRequest{}
	mi := &file_informer_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkersRequest) ProtoMessage() {}

func (x *GetWorkersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkersRequest.ProtoReflect.Descriptor instead.
func (*GetWorkersRequest) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkersRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type WorkersList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*ProcessState        `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkersList) Reset() {
	*x = WorkersList{}
	mi := &file_informer_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkersList) ProtoMessage() {}

func (x *WorkersList) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkersList.ProtoReflect.Descriptor instead.
func (*WorkersList) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *WorkersList) GetWorkers() []*ProcessState {
	if x != nil {
		return x.Workers
	}
	return nil
}

type GetJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobsRequest) Reset() {
	*x = GetJobsRequest{}
	mi := &file_informer_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobsRequest) ProtoMessage() {}

func (x *GetJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobsRequest.ProtoReflect.Descriptor instead.
func (*GetJobsRequest) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobsRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type JobsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*JobState            `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobsList) Reset() {
	*x = JobsList{}
	mi := &file_informer_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobsList) ProtoMessage() {}

func (x *JobsList) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobsList.ProtoReflect.Descriptor instead.
func (*JobsList) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *JobsList) GetStates() []*JobState {
	if x != nil {
		return x.States
	}
	return nil
}

type AddWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddWorkerRequest) Reset() {
	*x = AddWorkerRequest{}
	mi := &file_informer_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddWorkerRequest) ProtoMessage() {}

func (x *AddWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddWorkerRequest.ProtoReflect.Descriptor instead.
func (*AddWorkerRequest) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddWorkerRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type RemoveWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkerRequest) Reset() {
	*x = RemoveWorkerRequest{}
	mi := &file_informer_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkerRequest) ProtoMessage() {}

func (x *RemoveWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkerRequest.ProtoReflect.Descriptor instead.
func (*RemoveWorkerRequest) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveWorkerRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_informer_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_informer_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_informer_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_informer_v1_service_proto protoreflect.FileDescriptor

const file_informer_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x19informer/v1/service.proto\x12\vinformer.v1\"\xec\x01\n" +
	"\fProcessState\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x1b\n" +
	"\tnum_execs\x18\x03 \x01(\x04R\bnumExecs\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x03R\acreated\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x04R\vmemoryUsage\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x02R\n" +
	"cpuPercent\x12\x18\n" +
	"\acommand\x18\a \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"status_str\x18\b \x01(\tR\tstatusStr\"\xf9\x01\n" +
	"\bJobState\x12\x1a\n" +
	"\bpipeline\x18\x01 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x16\n" +
	"\x06active\x18\x04 \x01(\x03R\x06active\x12\x18\n" +
	"\adelayed\x18\x05 \x01(\x03R\adelayed\x12\x1a\n" +
	"\breserved\x18\x06 \x01(\x03R\breserved\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x04R\bpriority\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"\x14\n" +
	"\x12ListPluginsRequest\"'\n" +
	"\vPluginsList\x12\x18\n" +
	"\aplugins\x18\x01 \x03(\tR\aplugins\"+\n" +
	"\x11GetWorkersRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"B\n" +
	"\vWorkersList\x123\n" +
	"\aworkers\x18\x01 \x03(\v2\x19.informer.v1.ProcessStateR\aworkers\"(\n" +
	"\x0eGetJobsRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"9\n" +
	"\bJobsList\x12-\n" +
	"\x06states\x18\x01 \x03(\v2\x15.informer.v1.JobStateR\x06states\"*\n" +
	"\x10AddWorkerRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"-\n" +
	"\x13RemoveWorkerRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xfd\x02\n" +
	"\x0fInformerService\x12M\n" +
	"\vListPlugins\x12\x1f.informer.v1.ListPluginsRequest\x1a\x18.informer.v1.PluginsList\"\x03\x90\x02\x01\x12K\n" +
	"\n" +
	"GetWorkers\x12\x1e.informer.v1.GetWorkersRequest\x1a\x18.informer.v1.WorkersList\"\x03\x90\x02\x01\x12B\n" +
	"\aGetJobs\x12\x1b.informer.v1.GetJobsRequest\x1a\x15.informer.v1.JobsList\"\x03\x90\x02\x01\x12A\n" +
	"\tAddWorker\x12\x1d.informer.v1.AddWorkerRequest\x1a\x15.informer.v1.Response\x12G\n" +
	"\fRemoveWorker\x12 .informer.v1.RemoveWorkerRequest\x1a\x15.informer.v1.ResponseB\x85\x01Z=github.com/roadrunner-server/api-go/v6/informer/v1;informerV1\xca\x02\x1aRoadRunner\\Informer\\DTO\\V1\xe2\x02&RoadRunner\\Informer\\DTO\\V1\\GPBMetadatab\x06proto3"

var (
	file_informer_v1_service_proto_rawDescOnce sync.Once
	file_informer_v1_service_proto_rawDescData []byte
)

func file_informer_v1_service_proto_rawDescGZIP() []byte {
	file_informer_v1_service_proto_rawDescOnce.Do(func() {
		file_informer_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_informer_v1_service_proto_rawDesc), len(file_informer_v1_service_proto_rawDesc)))
	})
	return file_informer_v1_service_proto_rawDescData
}

var file_informer_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_informer_v1_service_proto_goTypes = []any{
	(*ProcessState)(nil),        // 0: informer.v1.ProcessState
	(*JobState)(nil),            // 1: informer.v1.JobState
	(*ListPluginsRequest)(nil),  // 2: informer.v1.ListPluginsRequest
	(*PluginsList)(nil),         // 3: informer.v1.PluginsList
	(*GetWorkersRequest)(nil),   // 4: informer.v1.GetWorkersRequest
	(*WorkersList)(nil),         // 5: informer.v1.WorkersList
	(*GetJobsRequest)(nil),      // 6: informer.v1.GetJobsRequest
	(*JobsList)(nil),            // 7: informer.v1.JobsList
	(*AddWorkerRequest)(nil),    // 8: informer.v1.AddWorkerRequest
	(*RemoveWorkerRequest)(nil), // 9: informer.v1.RemoveWorkerRequest
	(*Response)(nil),            // 10: informer.v1.Response
}
var file_informer_v1_service_proto_depIdxs = []int32{
	0,  // 0: informer.v1.WorkersList.workers:type_name -> informer.v1.ProcessState
	1,  // 1: informer.v1.JobsList.states:type_name -> informer.v1.JobState
	2,  // 2: informer.v1.InformerService.ListPlugins:input_type -> informer.v1.ListPluginsRequest
	4,  // 3: informer.v1.InformerService.GetWorkers:input_type -> informer.v1.GetWorkersRequest
	6,  // 4: informer.v1.InformerService.GetJobs:input_type -> informer.v1.GetJobsRequest
	8,  // 5: informer.v1.InformerService.AddWorker:input_type -> informer.v1.AddWorkerRequest
	9,  // 6: informer.v1.InformerService.RemoveWorker:input_type -> informer.v1.RemoveWorkerRequest
	3,  // 7: informer.v1.InformerService.ListPlugins:output_type -> informer.v1.PluginsList
	5,  // 8: informer.v1.InformerService.GetWorkers:output_type -> informer.v1.WorkersList
	7,  // 9: informer.v1.InformerService.GetJobs:output_type -> informer.v1.JobsList
	10, // 10: informer.v1.InformerService.AddWorker:output_type -> informer.v1.Response
	10, // 11: informer.v1.InformerService.RemoveWorker:output_type -> informer.v1.Response
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_informer_v1_service_proto_init() }
func file_informer_v1_service_proto_init() {
	if File_informer_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_informer_v1_service_proto_rawDesc), len(file_informer_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_informer_v1_service_proto_goTypes,
		DependencyIndexes: file_informer_v1_service_proto_depIdxs,
		MessageInfos:      file_informer_v1_service_proto_msgTypes,
	}.Build()
	File_informer_v1_service_proto = out.File
	file_informer_v1_service_proto_goTypes = nil
	file_informer_v1_service_proto_depIdxs = nil
}
