// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: status/v2/service.proto

package statusV2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/roadrunner-server/api-go/v6/status/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StatusServiceName is the fully-qualified name of the StatusService service.
	StatusServiceName = "status.v2.StatusService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StatusServiceStatusProcedure is the fully-qualified name of the StatusService's Status RPC.
	StatusServiceStatusProcedure = "/status.v2.StatusService/Status"
	// StatusServiceReadyProcedure is the fully-qualified name of the StatusService's Ready RPC.
	StatusServiceReadyProcedure = "/status.v2.StatusService/Ready"
)

// StatusServiceClient is a client for the status.v2.StatusService service.
type StatusServiceClient interface {
	Status(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error)
	Ready(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error)
}

// NewStatusServiceClient constructs a client for the status.v2.StatusService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStatusServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StatusServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	statusServiceMethods := v2.File_status_v2_service_proto.Services().ByName("StatusService").Methods()
	return &statusServiceClient{
		status: connect.NewClient[v2.StatusRequest, v2.StatusResponse](
			httpClient,
			baseURL+StatusServiceStatusProcedure,
			connect.WithSchema(statusServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		ready: connect.NewClient[v2.StatusRequest, v2.StatusResponse](
			httpClient,
			baseURL+StatusServiceReadyProcedure,
			connect.WithSchema(statusServiceMethods.ByName("Ready")),
			connect.WithClientOptions(opts...),
		),
	}
}

// statusServiceClient implements StatusServiceClient.
type statusServiceClient struct {
	status *connect.Client[v2.StatusRequest, v2.StatusResponse]
	ready  *connect.Client[v2.StatusRequest, v2.StatusResponse]
}

// Status calls status.v2.StatusService.Status.
func (c *statusServiceClient) Status(ctx context.Context, req *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// Ready calls status.v2.StatusService.Ready.
func (c *statusServiceClient) Ready(ctx context.Context, req *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error) {
	return c.ready.CallUnary(ctx, req)
}

// StatusServiceHandler is an implementation of the status.v2.StatusService service.
type StatusServiceHandler interface {
	Status(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error)
	Ready(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error)
}

// NewStatusServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStatusServiceHandler(svc StatusServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	statusServiceMethods := v2.File_status_v2_service_proto.Services().ByName("StatusService").Methods()
	statusServiceStatusHandler := connect.NewUnaryHandler(
		StatusServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(statusServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	statusServiceReadyHandler := connect.NewUnaryHandler(
		StatusServiceReadyProcedure,
		svc.Ready,
		connect.WithSchema(statusServiceMethods.ByName("Ready")),
		connect.WithHandlerOptions(opts...),
	)
	return "/status.v2.StatusService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StatusServiceStatusProcedure:
			statusServiceStatusHandler.ServeHTTP(w, r)
		case StatusServiceReadyProcedure:
			statusServiceReadyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStatusServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStatusServiceHandler struct{}

func (UnimplementedStatusServiceHandler) Status(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("status.v2.StatusService.Status is not implemented"))
}

func (UnimplementedStatusServiceHandler) Ready(context.Context, *connect.Request[v2.StatusRequest]) (*connect.Response[v2.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("status.v2.StatusService.Ready is not implemented"))
}
