// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tcp/v1/service.proto

package tcpV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TCPService_Close_FullMethodName = "/tcp.v1.TCPService/Close"
)

// TCPServiceClient is the client API for TCPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TCPService exposes runtime control over open TCP connections handled by the
// tcp plugin. Close terminates a single connection identified by its UUID.
type TCPServiceClient interface {
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Response, error)
}

type tCPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTCPServiceClient(cc grpc.ClientConnInterface) TCPServiceClient {
	return &tCPServiceClient{cc}
}

func (c *tCPServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, TCPService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TCPServiceServer is the server API for TCPService service.
// All implementations must embed UnimplementedTCPServiceServer
// for forward compatibility.
//
// TCPService exposes runtime control over open TCP connections handled by the
// tcp plugin. Close terminates a single connection identified by its UUID.
type TCPServiceServer interface {
	Close(context.Context, *CloseRequest) (*Response, error)
	mustEmbedUnimplementedTCPServiceServer()
}

// UnimplementedTCPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTCPServiceServer struct{}

func (UnimplementedTCPServiceServer) Close(context.Context, *CloseRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedTCPServiceServer) mustEmbedUnimplementedTCPServiceServer() {}
func (UnimplementedTCPServiceServer) testEmbeddedByValue()                    {}

// UnsafeTCPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TCPServiceServer will
// result in compilation errors.
type UnsafeTCPServiceServer interface {
	mustEmbedUnimplementedTCPServiceServer()
}

func RegisterTCPServiceServer(s grpc.ServiceRegistrar, srv TCPServiceServer) {
	// If the following call panics, it indicates UnimplementedTCPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TCPService_ServiceDesc, srv)
}

func _TCPService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TCPServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TCPService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TCPServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TCPService_ServiceDesc is the grpc.ServiceDesc for TCPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TCPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tcp.v1.TCPService",
	HandlerType: (*TCPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Close",
			Handler:    _TCPService_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tcp/v1/service.proto",
}
