// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tcp/v1/service.proto

package tcpV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_tcp_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_tcp_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CloseRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tcp_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tcp_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_tcp_v1_service_proto protoreflect.FileDescriptor

const file_tcp_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14tcp/v1/service.proto\x12\x06tcp.v1\"\"\n" +
	"\fCloseRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02okBqZ3github.com/roadrunner-server/api-go/v6/tcp/v1;tcpV1\xca\x02\x15RoadRunner\\TCP\\DTO\\V1\xe2\x02!RoadRunner\\TCP\\DTO\\V1\\GPBMetadatab\x06proto3"

var (
	file_tcp_v1_service_proto_rawDescOnce sync.Once
	file_tcp_v1_service_proto_rawDescData []byte
)

func file_tcp_v1_service_proto_rawDescGZIP() []byte {
	file_tcp_v1_service_proto_rawDescOnce.Do(func() {
		file_tcp_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcp_v1_service_proto_rawDesc), len(file_tcp_v1_service_proto_rawDesc)))
	})
	return file_tcp_v1_service_proto_rawDescData
}

var file_tcp_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tcp_v1_service_proto_goTypes = []any{
	(*CloseRequest)(nil), // 0: tcp.v1.CloseRequest
	(*Response)(nil),     // 1: tcp.v1.Response
}
var file_tcp_v1_service_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcp_v1_service_proto_init() }
func file_tcp_v1_service_proto_init() {
	if File_tcp_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcp_v1_service_proto_rawDesc), len(file_tcp_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcp_v1_service_proto_goTypes,
		DependencyIndexes: file_tcp_v1_service_proto_depIdxs,
		MessageInfos:      file_tcp_v1_service_proto_msgTypes,
	}.Build()
	File_tcp_v1_service_proto = out.File
	file_tcp_v1_service_proto_goTypes = nil
	file_tcp_v1_service_proto_depIdxs = nil
}
