// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: lock/v1/service.proto

package lockV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_lock_v1_service_proto protoreflect.FileDescriptor

const file_lock_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15lock/v1/service.proto\x12\alock.v1\x1a\x12lock/v1/lock.proto2\xe6\x02\n" +
	"\vLockService\x123\n" +
	"\x04Lock\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponse\x127\n" +
	"\bLockRead\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponse\x126\n" +
	"\aRelease\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponse\x12;\n" +
	"\fForceRelease\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponse\x12:\n" +
	"\x06Exists\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponse\"\x03\x90\x02\x01\x128\n" +
	"\tUpdateTTL\x12\x14.lock.v1.LockRequest\x1a\x15.lock.v1.LockResponseBuZ5github.com/roadrunner-server/api-go/v6/lock/v1;lockV1\xca\x02\x16RoadRunner\\Lock\\DTO\\V1\xe2\x02\"RoadRunner\\Lock\\DTO\\V1\\GPBMetadatab\x06proto3"

var file_lock_v1_service_proto_goTypes = []any{
	(*LockRequest)(nil),  // 0: lock.v1.LockRequest
	(*LockResponse)(nil), // 1: lock.v1.LockResponse
}
var file_lock_v1_service_proto_depIdxs = []int32{
	0, // 0: lock.v1.LockService.Lock:input_type -> lock.v1.LockRequest
	0, // 1: lock.v1.LockService.LockRead:input_type -> lock.v1.LockRequest
	0, // 2: lock.v1.LockService.Release:input_type -> lock.v1.LockRequest
	0, // 3: lock.v1.LockService.ForceRelease:input_type -> lock.v1.LockRequest
	0, // 4: lock.v1.LockService.Exists:input_type -> lock.v1.LockRequest
	0, // 5: lock.v1.LockService.UpdateTTL:input_type -> lock.v1.LockRequest
	1, // 6: lock.v1.LockService.Lock:output_type -> lock.v1.LockResponse
	1, // 7: lock.v1.LockService.LockRead:output_type -> lock.v1.LockResponse
	1, // 8: lock.v1.LockService.Release:output_type -> lock.v1.LockResponse
	1, // 9: lock.v1.LockService.ForceRelease:output_type -> lock.v1.LockResponse
	1, // 10: lock.v1.LockService.Exists:output_type -> lock.v1.LockResponse
	1, // 11: lock.v1.LockService.UpdateTTL:output_type -> lock.v1.LockResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lock_v1_service_proto_init() }
func file_lock_v1_service_proto_init() {
	if File_lock_v1_service_proto != nil {
		return
	}
	file_lock_v1_lock_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lock_v1_service_proto_rawDesc), len(file_lock_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lock_v1_service_proto_goTypes,
		DependencyIndexes: file_lock_v1_service_proto_depIdxs,
	}.Build()
	File_lock_v1_service_proto = out.File
	file_lock_v1_service_proto_goTypes = nil
	file_lock_v1_service_proto_depIdxs = nil
}
